// Pallet Town and its interiors.
(function () {
  const M = window.MAPS = window.MAPS || {};
  M.pallet = {
    name: 'PALLET TOWN', era: 0, music: 'pallet', border: 'tree',
    rows: [
      'TTTTTTTTTT..TTTTTTTT',
      'T.........==.......T',
      'T.1223....==..1223.T',
      'T.[XD]....==..[XD].T',
      'T...=======.===....T',
      'T...=.....=...=....T',
      'T.f.=..S..=...=.f..T',
      'T...=..122223.=....T',
      'T...=..455556.=....T',
      'T...=..[XADX].=....T',
      'T...=======S===....T',
      'T....f...=....f....T',
      'T.-----..=..-----..T',
      'T.~~~~|..=..|..b...T',
      'T.~~~~|..=..|......T',
      'T.~~~~|..=..|..f...T',
      'T.....|..=..|......T',
      'T~~~~~~~~=~~~~~~~~~T',
    ],
    exits: [{ edge: 'north', from: 10, to: 11, map: 'route1', offset: 0 }],
    objects: [
      { type: 'warp', x: 4, y: 3, map: 'player_house_1f', tx: 4, ty: 7, dir: 'up' },
      { type: 'warp', x: 16, y: 3, map: 'friend_house', tx: 4, ty: 7, dir: 'up' },
      { type: 'warp', x: 10, y: 9, map: 'lab', tx: 5, ty: 9, dir: 'up' },
      { type: 'sign', x: 7, y: 6, text: ['PALLET TOWN', 'A quiet start to a kind journey.'] },
      { type: 'sign', x: 11, y: 10, text: ['OAT ANIMAL RESEARCH LAB', 'No animal is a specimen here. They are colleagues.'] },
      { type: 'trigger', x: 10, y: 0, w: 2, h: 1, script: 'prof_stop' },
      { type: 'trigger', x: 10, y: 1, w: 2, h: 1, script: 'prof_stop' },
      { type: 'npc', id: 'pallet_girl', x: 13, y: 5, sprite: 'girl', pal: { t: '#e05070', h: '#a05020' }, dir: 'down', move: 'wander', range: 2,
        dialog: G => G.flag('starter') ? ['I heard you got an animal from PROF. OAT!', 'Feed them what they love and they will trust you fast.'] : ['I\'m raising a BUNNY! It\'s so soft!', 'Technically it\'s raising me.'] },
      { type: 'npc', id: 'pallet_oldman', x: 3, y: 11, sprite: 'oldman', dir: 'left', move: 'look',
        dialog: ['I swim in this pond every morning.', 'The water is lovely. The ducks disagree.'] },
      { type: 'npc', id: 'pallet_kid', x: 15, y: 14, sprite: 'kid', pal: { a: '#3050c0' }, dir: 'down', move: 'wander', range: 2,
        dialog: ['Everything here is black and white...', 'Mom says the world gets colorful when you head north!'] },
      // ---- team members: the first birthday wishes, before the world turns colour
      { type: 'npc', id: 'pallet_ximena', team: 'ximena', x: 7, y: 4, dir: 'down', move: 'wander', range: 2 },
      { type: 'npc', id: 'pallet_steven', team: 'steven', x: 13, y: 4, dir: 'down', move: 'wander', range: 2 },
      { type: 'npc', id: 'pallet_richie', team: 'richie', x: 6, y: 10, dir: 'up', move: 'wander', range: 2 },
      { type: 'npc', id: 'pallet_mike', team: 'mike', x: 14, y: 10, dir: 'up', move: 'wander', range: 2 },
      { type: 'npc', id: 'pallet_aaron', team: 'aaron', x: 3, y: 6, dir: 'right', move: 'wander', range: 2 },
      { type: 'item', id: 'pallet_bean1', x: 17, y: 13, item: 'VEGAN BEANS', hidden: true },
      { type: 'item', id: 'pallet_bean2', x: 2, y: 16, item: 'VEGAN BEANS', hidden: true },
      { type: 'item', id: 'pallet_mooch', x: 17, y: 16, item: 'NOOCH', qty: 1 },
    ],
  };

  M.player_house_1f = {
    name: "JAMES'S HOUSE", era: 0, music: 'pallet', indoor: true, border: 'void',
    rows: [
      'wwwwxwww',
      'hRQooooo',
      'ooooooo/',
      'oocaadoo',
      'oooooooo',
      'oooooooo',
      'otoooooo',
      'ooooKooo'.replace('K', 'm'),
    ],
    objects: [
      { type: 'warp', x: 4, y: 7, map: 'pallet', tx: 4, ty: 4, dir: 'down' },
      { type: 'warp', x: 7, y: 2, map: 'player_house_2f', tx: 6, ty: 1, dir: 'left' },
      { type: 'npc', id: 'mom', name: 'ABBIE', x: 5, y: 4, sprite: 'abbie', dir: 'down', move: 'wander', range: 1, script: 'mom' },
      { type: 'interact', x: 0, y: 1, text: ['Cookbooks. Every recipe has been veganized with a pencil.'] },
      { type: 'interact', x: 1, y: 1, text: ['The fridge is full of oat milk, tofu, and a suspicious amount of hummus.'] },
      { type: 'interact', x: 2, y: 1, text: ['Something is simmering. Smells like lentils and love.'] },
    ],
  };
  M.player_house_2f = {
    name: "JAMES'S ROOM", era: 0, music: 'pallet', indoor: true, border: 'void',
    rows: [
      'wwwwxwww',
      'BPooooo\\',
      'Eooooooo',
      'oooooooo',
      'otoooooo',
      'oooooooo',
      'ouuooooo',
      'oooooooo',
    ],
    objects: [
      { type: 'warp', x: 7, y: 1, map: 'player_house_1f', tx: 6, ty: 2, dir: 'left' },
      { type: 'interact', x: 0, y: 2, text: ['A cozy bed with a pigeon-pattern blanket. The pillow still has the shape of a very long nap.'] },
    ],
  };
  M.friend_house = {
    name: "DAVID'S HOUSE", era: 0, music: 'pallet', indoor: true, border: 'void',
    rows: [
      'wwwwxwww',
      'hhoooooo',
      'oooooooo',
      'oocaadoo',
      'oooooooo',
      'oosooooo',
      'oooooqoo',
      'ooooKooo'.replace('K', 'm'),
    ],
    objects: [
      { type: 'warp', x: 4, y: 7, map: 'pallet', tx: 16, ty: 4, dir: 'down' },
      { type: 'npc', id: 'friend_sis', x: 5, y: 4, sprite: 'woman', pal: { t: '#8858c8', h: '#402810' }, dir: 'down', move: 'look',
        dialog: G => G.flag('starter') ? [G.state.rival + ' rushed out talking about rescuing MORE animals than you.', 'He left his handpan. Again.'] : ['Hi ' + G.state.name + '! ' + G.state.rival + ' is over at PROF. OAT\'s lab.', 'He\'s been there since 6 AM. Something about a "big idea".'] },
      { type: 'interact', x: 0, y: 1, text: ['Shelves of anime, philosophy, and one book titled "How To Let Go (Of The Nonprofit You Founded)".'] },
      { type: 'interact', x: 1, y: 1, text: ['A handpan rests on the shelf. It hums faintly when you look at it.'] },
      { type: 'interact', x: 2, y: 5, text: ['A very comfortable sofa. There is a laptop wedged in the cushions. Still running.'] },
    ],
  };
  M.lab = {
    name: 'OAT LAB', era: 0, music: 'lab', indoor: true, border: 'void',
    rows: [
      'wwwwvwwwww',
      'hhoooooooh',
      'oooooooooo',
      'oooooooooo',
      'oooooooooo',
      'oooooilili',
      'oooooooooo',
      'heooooooeh',
      'oooooooooo',
      'oooooKoooo'.replace('K', 'm'),
    ],
    objects: [
      { type: 'warp', x: 5, y: 9, map: 'pallet', tx: 10, ty: 10, dir: 'down' },
      { type: 'npc', id: 'prof', x: 2, y: 2, sprite: 'prof', dir: 'down', move: 'static', script: 'lab_prof' },
      { type: 'npc', id: 'rival', x: 7, y: 7, sprite: 'hoodie', dir: 'up', move: 'static', unless: 'starter',
        dialog: G => G.flag('choose_starter') ? [G.state.rival + ': Go on, pick one! I\'ll take the one you don\'t.', G.state.rival + ': That\'s called strategy.'] : [G.state.rival + ': Yo ' + G.state.name + '! PROF. OAT isn\'t around yet.', G.state.rival + ': I have a BIG IDEA. It involves a spreadsheet.'] },
      { type: 'npc', id: 'lab_aide', x: 8, y: 2, sprite: 'man', pal: { t: '#e8e8e8', a: '#e8e8e8', h: '#503020' }, dir: 'down', move: 'look',
        dialog: ['I\'m the PROF\'s aide. I study animal happiness.', 'Findings so far: belly rubs, 10 out of 10.'] },
      { type: 'interact', x: 5, y: 5, script: 'pick_starter', species: 'TOAD' },
      { type: 'interact', x: 7, y: 5, script: 'pick_starter', species: 'SALAMANDER' },
      { type: 'interact', x: 9, y: 5, script: 'pick_starter', species: 'TURTLE' },
      { type: 'interact', x: 0, y: 1, text: ['"The Compassionate Field Guide to Farm Animals", volumes 1 through 12.'] },
      { type: 'interact', x: 1, y: 1, text: ['Research notes: "Chickens can recognize over 100 faces. They remember yours."'] },
      { type: 'interact', x: 9, y: 1, text: ['A framed photo of the PROF hugging a very large cow. Both are smiling.'] },
      { type: 'interact', x: 1, y: 7, text: ['The PROF\'s desk. A half-eaten NOOCH sandwich sits on a stack of papers.'] },
      { type: 'interact', x: 8, y: 7, text: ['A computer. The screen shows the FRIENDDEX database: 18 entries, all marked "friend".'] },
    ],
  };
})();
