// Gen 3-style trainer battle sprites, imported pixel-for-pixel by tools/fit_sprite.py + tools/import_sheet.py.
// Loaded after sprites_trainers.js so these replace the hand-drawn versions of the same names.
// Each palette entry carries its Game Boy shade (:0-:3), which is what era 0 draws in Pallet Town.
(function () {
  const S = window.SPRITES = window.SPRITES || {};
  const PAL = { 'a': '#bd9473:2', 'b': '#e6c5a4:3', 'c': '#ffeed5:3', 'd': '#6a5a41:1', 'e': '#9c94ac:2', 'f': '#736a83:1', 'g': '#ded5ee:2', 'h': '#000000:0', 'i': '#eee6f6:2', 'j': '#9c836a:2', 'k': '#bdac8b:2', 'l': '#c58b39:2', 'm': '#decd9c:3', 'n': '#946a20:1' };
  S['front_grandpa'] = { w: 48, h: 48, pal: PAL, rows: [
    '...................abbaa........................',
    '.................abcccbbd.......................',
    '................accccccbef......................',
    '................ccccccccbae.....................',
    '...............accccccccbegh....................',
    '...............eiccciiigbaggf...................',
    '...............eigcciigebefggf..................',
    '...............hgiccebbbbfceg...................',
    '...............hbbccbbbbbabfgh..................',
    '...............ddaccddbbbdafe...................',
    '................dcccbccbdheh....................',
    '................ddbccbbbhff.....................',
    '.................dbdabdaf.......................',
    '..................dbbbdhhh......................',
    '..................hdhhajhjhhd...................',
    '................hdjddjkkldkmm...................',
    '................hknjkjjdldmmmd..................',
    '................hjljkjknldmmmj..................',
    '................hjnlddjlljkmmjd.................',
    '.................hlllllllnjkjkh.................',
    '..................dllllllldhjjjdd...............',
    '...................nlllllllnhjjjh...............',
    '...................dlllllllnhjjkk...............',
    '....................lllllllnddkkk...............',
    '....................llllnllnljjjd...............',
    '....................nllllnnlndhh................',
    '....................nnnnnnnnnh..................',
    '....................hdnnnndhh...................',
    '....................ddhhddnnd...................',
    '....................dddhnnnnn...................',
    '....................nddhnnnnn...................',
    '....................ndddnnnnn...................',
    '...................hndddnnnnn...................',
    '...................dndddnnnnn...................',
    '...................dnddddnnnn...................',
    '...................dddddhnnnn...................',
    '...................hdddhhnndn...................',
    '...................hdddhhnndn...................',
    '...................hdddhhndnn...................',
    '....................dddhdnnnn...................',
    '....................dddh.dnnd...................',
    '....................dddh.dnnd...................',
    '....................dddd.ddndh..................',
    '....................dddd.ddddh..................',
    '...................fhddd.hdddh..................',
    '..................hefhdh.hffhh..................',
    '..................hfffhhhfeefh..................',
    '..................hhhhh.hffffh..................',
  ] };
})();
(function () {
  const S = window.SPRITES = window.SPRITES || {};
  const PAL = { 'a': '#070707:0', 'b': '#736a83:1', 'c': '#524a62:1', 'd': '#7b6252:1', 'e': '#bd947b:2', 'f': '#f6dec5:3', 'g': '#d5b49c:2', 'h': '#9c94ac:2', 'i': '#ffffff:3', 'j': '#ded5ee:3', 'k': '#bdb4cd:2' };
  S['front_gymbro'] = { w: 48, h: 48, pal: PAL, rows: [
    '.......................aaaaa....................',
    '.....................aabbcccaa..................',
    '.....................abbbbcccb..................',
    '...............dda..acbbbccccba.................',
    '.............effggg.dgccgffgcca.................',
    '.............effeef.degfffcgbaa.................',
    '.............dgdddd.accfecggbdca................',
    '.............dggeg...agfffgbcgca................',
    '.............dfa.....defffffeaaa................',
    '.............dfa.....aggfefffca.................',
    '............effa......adeffeaa..................',
    '............dfga......dffadaaa..................',
    '...........efffdaadffdhgffgciidaa...............',
    '...........dfffdgfffdiifffciiifffd..............',
    '...........agffeggghiiiiiihiiiffff..............',
    '.............agggggaiiieiiiiidffefffd...........',
    '..............dadggaiiiddhiijdffggega...........',
    '................aaaajiideijjhjggggggg...........',
    '...................ahjjdiihjjjaaggggg...........',
    '....................hiiiiiiijj...afgf...........',
    '....................aiiiiiiiij...affd...........',
    '....................ajiiiiiiih..dffga...........',
    '....................aijjiiiija.ddffd............',
    '....................ajjjiiidffeggea.............',
    '....................aajiiidfggfgaa..............',
    '....................hjahhhagfeaa................',
    '...................ajikkhjiiaaa.................',
    '...................aiijjhiiiii..................',
    '...................aiijjhjiiiia.................',
    '...................hiijjaiiiiih.................',
    '...................jijjjjaiiiiia................',
    '...................jjjjja.jiiiiia...............',
    '...................ahjjja.kiiiiia...............',
    '...................ffgdaa.hjihhaa...............',
    '...................ffffa...afffa................',
    '...................ffffa...dfffa................',
    '...................ffed....dfffd................',
    '...................gfgg....afffgd...............',
    '...................dggg.....dfgga...............',
    '...................dggg.....dggga...............',
    '...................agg.......aggga..............',
    '...................agga.......ggga..............',
    '...................agga.......egga..............',
    '...................agga.......agga..............',
    '..................aaega.......agga..............',
    '...............acccbcca.......abbc..............',
    '...............aaaccaaa......acccb..............',
    '...............aaaaaa........aaaaa..............',
  ] };
})();
(function () {
  const S = window.SPRITES = window.SPRITES || {};
  const PAL = { 'a': '#35313e:1', 'b': '#742320:1', 'c': '#000000:0', 'd': '#d47363:2', 'e': '#d45742:1', 'f': '#ad3f30:1', 'g': '#cc8c7c:2', 'h': '#93615d:1', 'i': '#785850:1', 'j': '#f8f8f8:3', 'k': '#793e3f:1', 'l': '#646464:1', 'm': '#b9b9b9:2', 'n': '#2a3950:1', 'o': '#e88060:2', 'p': '#a0b0b8:2', 'q': '#101a2a:0', 'r': '#c83850:1', 's': '#ffffff:3', 't': '#0d131b:0', 'u': '#8d704a:1', 'v': '#d0d298:3', 'w': '#b69e64:2' };
  S['front_influencer'] = { w: 48, h: 48, pal: PAL, rows: [
    '.............................aaa................',
    '........................bbbbcaac................',
    '......................ddddddebcbac..............',
    '.....................ddddddeebfca...............',
    '....................bddedeeefeef................',
    '....................ceddeebbddddb...............',
    '....................ebbbcgghbdddb...............',
    '....................beiaggaabeeeb...............',
    '.....................ijcgajchbee................',
    '.....................chgggghhbb.................',
    '....................fchkgggglc..................',
    '...................ccfchjjkhcfc.................',
    '..................iccmfchhhcffnc................',
    '.................iigiocfpqqqfnnc................',
    '.................igirrcccmmnncc.................',
    '.................kggijcsnsssnt..................',
    '...............ccggijcmnnnsssqt.................',
    '...............cchkccmsnnnqsnnn.................',
    '...............cbcctcqqnnnqtnnnq................',
    '..............tnffbkfbctnnqnqqt.................',
    '..............qnnqckfebnctnnnnc.................',
    '..............qnqccifbqnnnnnnc..................',
    '..............cqqc.ccbqqqnnnc...................',
    '...............cc..cuccqqqqc....................',
    '...................cupvccttc....................',
    '..................cupvvvwwucc...................',
    '..................cupccccccuc...................',
    '..................ccpvvwwuuuc...................',
    '..................cbccccccccc...................',
    '..................cbtbtnnenn....................',
    '..................cbtbnnnenn....................',
    '..................cbttenneee....................',
    '..................cttttnnnnnc...................',
    '..................cttttcnnnnc...................',
    '..................cttttcnnnnc...................',
    '..................ccctttccccc...................',
    '...................chhcc.cggc...................',
    '...................chhhc..cgc...................',
    '....................chhc..chhc..................',
    '....................ckhc..chhc..................',
    '....................chhh..ckhkc.................',
    '...................chnqc..chhhc.................',
    '...................ccqqc.cccccc.................',
    '..................ccnnqc..cqqqc.................',
    '.................qqwsmqc..cmmqc.................',
    '................qnnnecqc..cqqc..................',
    '................cnnceee..cqnnqc.................',
    '..........................cccc..................',
  ] };
})();
(function () {
  const S = window.SPRITES = window.SPRITES || {};
  const PAL = { 'a': '#684848:1', 'b': '#000000:0', 'c': '#c07808:1', 'd': '#d8a048:2', 'e': '#c08868:2', 'f': '#e8b090:2', 'g': '#f8d8c8:3', 'h': '#705080:2', 'i': '#9868a8:2', 'j': '#304050:1', 'k': '#687880:1', 'l': '#c0c8b0:3', 'm': '#f8f8f8:3', 'n': '#c888f8:2' };
  S['front_rival'] = { w: 48, h: 48, pal: PAL, rows: [
    '.........................a.....ba...............',
    '.........................c....bca...............',
    '........................bdabbcdd................',
    '.....................babadbcdddcaacc............',
    '.....................bdaddccccccccca............',
    '.....................bdddddcccccccb.............',
    '......................adddddddccccccca..........',
    '......................bdddccdddcacccb...........',
    '.......................addaccaaccacc............',
    '.......................bbaeadceedcac............',
    '......................bdfaebacebaeaa............',
    '............b........bdbffgbeeeffaac............',
    '...........bgb..........baegggefb...............',
    '..........baahbbeee......bageaffb...............',
    '.........bffefhihggeebbbbjkkaefa................',
    '.........befaeeibgggfebkkjkkebbb................',
    '.............ba...bbefjkkkkkejjb................',
    '....................bjkjkkkkjjkb................',
    '.....................bbbjkkkkkjk................',
    '.......................bbjkkkkjkb...............',
    '.........................bjjkkkkb...............',
    '.........................bjjjjjkj...............',
    '.........................bjjjkkjb...............',
    '..........................jjjjjkbb..aa..........',
    '..........................bjjjjjjb.bbfa.........',
    '.........................kkkllkkbbkbfeg.........',
    '........................kmmmmlklbbbeefe.........',
    '.......................klllllkkjjjbeebb.........',
    '.......................kmmmmllbjjjb.............',
    '........................lmmmlkhbhhhb............',
    '........................bkkkkbhbhhhb............',
    '........................biiiiihhhhhb............',
    '.......................hnnhnnibhhhhh............',
    '.......................hnninnhbhhhhh............',
    '.......................hhhnnnbbhhhhh............',
    '.......................hnnnnib.bhhhhb...........',
    '.......................hinnnh..bhhhhb...........',
    '.......................hinni...hhhhhb...........',
    '.......................hinni...bhhhib...........',
    '......................hihiib...bhhii............',
    '.....................hiiiib....bhhii............',
    '.....................hihihb....bhhii............',
    '....................hihiiib....bhhhh............',
    '....................hihihb.....bhhhhb...........',
    '....................bihhhb.....bhhhib...........',
    '.....................hhhb.......bhjjkb..........',
    '....................bjjkbb.......bbjjjb.........',
    '....................bjjjjb.........bbb..........',
  ] };
})();
(function () {
  const S = window.SPRITES = window.SPRITES || {};
  const PAL = { 'a': '#f2ebf2:3', 'b': '#ecdaeb:3', 'c': '#c3afb8:2', 'd': '#e5cddd:3', 'e': '#b7989a:2', 'f': '#6e5867:1', 'g': '#584c59:1', 'h': '#84757f:1', 'i': '#48383f:0', 'j': '#f1e0f2:3', 'k': '#2c2026:0', 'l': '#cfc8d0:3', 'm': '#ab8281:2' };
  S['front_cheeselover'] = { w: 48, h: 48, pal: PAL, rows: [
    '........................aabccb..................',
    '.......................bdcefgha.................',
    '....................abbihhcjjka.................',
    '...................ablfebjjjamfba...............',
    '...................bchcdjjbegcgigbb.............',
    '..................acgdjjjbffmilllifa............',
    '.................blgjjjjjchihmillalh............',
    '.................chbbjbjjhfmkmkkgjdk............',
    '................blfjjjjbcffmgelgiceg............',
    '................lgdjjjjjmiljbjdkicia............',
    '................ckjbjjjgiebjjjlkieci............',
    '................ckjjbjmkiedjjlieiiil............',
    '................ckdjjjgmeielbhkckc..............',
    '................ckcjjahfcghflbflmd..............',
    '...............aefhjjjjglmjjeembcl..bdl.........',
    '...............lklhdcebcmdjjffhlhababehda.......',
    '..............afhbejeejjkedjgedfcjbhfeehl.......',
    '.............acfdmbbdelfiihbclgcalfccbblh.......',
    '.............acgbebjjhhhicffhil.ahcjcfhhg.......',
    '...........dllgbhdbadfkhhbjgkcalaialihkkc.......',
    '..........ddhhhllbjjefekajjjhifhecbfhfheb.......',
    '..........bfhedebjjlmmefalcjacgifldg.lca........',
    '........dbliddejjjdmeemmgdhejjcicagl............',
    '.......dcfkebcdbjbheemmeefdgejbbjdha............',
    '.......lhhdjdmjjbhemmmmicfffkcbjjid.............',
    '.......bmhdbcbjdeeemmmgcffifgiedchb.............',
    '.......abfclmbbhmmeemhcdimhhffiffl..............',
    '.......lfcehbbcfmeccchcfeffefffkh...............',
    '.......lhghidjcgmeclhmakmighmhfima..............',
    '........ab.bkdbcdedembechicehfffgca.............',
    '...........cklcmelcmhafcekheehggghb.............',
    '...........lghgimcmfamejhihfhhikiieb............',
    '............ch.dhhhadfcbigggcjdfhbhc............',
    '................lhalfejcelghdjblflbga...........',
    '..............ablddgejjgaalfejjblflee...........',
    '..............deiidmielceaaliebjjcgcgb..........',
    '..............ciegicigkmeaaalimbbjlhce..........',
    '..............ckffkdefciaabekmkebjdieg..........',
    '..............cgeegabfkmegkmmmhibjjlkf..........',
    '...............dee.lhifggfhhihhldbdgfd..........',
    '...................lifffkkkfmldjbfhld...........',
    '...................ckfielhgcdddlicb.............',
    '...................ckfkkkglldikh................',
    '...................cigkkelcfhb..................',
    '...................bekkkchkc....................',
    '....................lfikhchl....................',
    '....................bclikhfgd...................',
    '......................dckkakl...................',
  ] };
})();
(function () {
  const S = window.SPRITES = window.SPRITES || {};
  const PAL = { 'a': '#eee8ec:3', 'b': '#e8d3df:3', 'c': '#c3b6c1:2', 'd': '#7d686e:1', 'e': '#c2978f:2', 'f': '#392b31:0', 'g': '#694d50:1', 'h': '#e0babc:2', 'i': '#181314:0', 'j': '#514148:1', 'k': '#ad8580:2', 'l': '#9f746e:1', 'm': '#f2def2:3' };
  S['front_bbqdad'] = { w: 48, h: 44, pal: PAL, rows: [
    '...................aab...aac....................',
    '...................bdea.aaeda...................',
    '..................aafgebahgid...................',
    '................ababfijccdiidabca...............',
    '................cjdjiiifiiiifdfij...............',
    '.............baaciiiiiiiiiiiiiiif...............',
    '.............cddkiiiiiiiiiiiiiiid...............',
    '.............hkfiiiiiiiiiiiiiiifkcaa............',
    '.............bbjiiiiiiiiiiiiiiiiife.............',
    '..............akfiiiiiiiiiiiiiiiflh.............',
    '.............aabdiiiiiiiiiiiiiiidl..............',
    '............badfiiddiiiddfiigkgffdbb............',
    '...........badjllfebccmbbccchbeflkddca..........',
    '..........acfkhegjflbbbbbmmbejjgebhkjha.........',
    '.........bkjkmmdgkjffdlllkdjijlggmmmkjk.........',
    '.........bidikbgelflifeekhjiddgejkcdfdf.........',
    '.........bdfgdhcglgeddgeedddbdlgdkcgjfd.........',
    '........cbfehjkmcgjelhhehkbbeggkjmkjhed.........',
    '........cdkbmgdbbeglkeelcbhkfelfbbdgmbj.........',
    '......abbgmbhdfemblfdkkiidhddkklbefkmmdbba......',
    '.....bcjfjbhekedmmhdckfkkggjcdbmbdklhheffgca....',
    '..aabefgkgellehfbmmhgcdkkgdbgcmmcfekllkgkgfkaa..',
    '.abdjfiiglekkggfhbmbgbcgegcbgbmmcifgkkedgiifgba.',
    'abkgellfileeekjjebmmegbjgjcjemmmcjfekeedifdeekcb',
    'bkijdklkjfehdacjlebmmfegjecdeehbejcadhefjkledjij',
    'afdifjfkdfekdkjgjlebhllggejeeekljdgeglkfdkfjfigi',
    'aflgejjdjfldbleelflldgijjdjddllgmmmcbgdfjljjegkj',
    'ajflhdfkgjekegeeeekdfiiiiiiifdcbmmcdkkkjglfgbljd',
    '.cjffjcijcfkhkjebmbhellgfllkhmmmmcjkeljcjicjffjc',
    '.aakickfemdbbbedgbmmhhhjjfkehmmbflebbedmefccikb.',
    '...adffebeemmmbhljbmmcfkkkfkeeejebmmmbeeaeffd...',
    '.......acgbmmmmmedgckfjjjfffglgdbmmmmmbgca......',
    '.......cklbmmmmmheldfjjddddkgjlemmmmmmmedb......',
    '........bkhmmmmmbeedjeb....acflemmmmmmmbdk......',
    '......aaaddhmmmmhedd........aajlebmmmmmkfe......',
    '......acjgbbmbbcedd...........agebmmmmmedca.....',
    '......bddgcceelfgj.............bdebbmmhgekca....',
    '......afgcdffjebkc...........aacfeeebbecekfa....',
    '......beecfekkbmcd...........cdgdlglkljjeec.....',
    '.....aagggleebcgkc...........cddcgfjflklcc......',
    '.....bkkkkeehcccba............ababdjlebhdkb.....',
    '......bgfbbbjb....................mkdlehhdca....',
    '..................................cdefkllhfa....',
    '..................................cglkdddkk.....',
  ] };
})();
(function () {
  const S = window.SPRITES = window.SPRITES || {};
  const PAL = { 'a': '#f0e5f0:3', 'b': '#eedcee:3', 'c': '#decddd:3', 'd': '#b7a6b2:2', 'e': '#99899a:2', 'f': '#7a6d78:1', 'g': '#5b4549:1', 'h': '#402f35:0', 'i': '#6d5963:1', 'j': '#dfa390:2', 'k': '#99716f:1', 'l': '#241a1e:0', 'm': '#c98c75:2' };
  S['front_chef'] = { w: 48, h: 44, pal: PAL, rows: [
    '...................abcddddca....................',
    '..................acefghhgfecc..................',
    '.................bdefcedceceeeb.................',
    '................acecbbeabecbbed.................',
    '...............aceeeffieffffedic................',
    '..............caggjccccccccccjkfd...............',
    '.............beibcdcgllhhllhddcffc..............',
    '.............ceddilgmkhkmgimilhdcf..............',
    '.............cdfglfjhggikggijelhfe..............',
    '.............acdehdfffkccefficgffd..............',
    '.............cfdgdadcabdebbbdadgcga.............',
    '..........abcceehkbflieeeefliaehef..............',
    '.......cdaceeecfhgebfedeedeicdfhicdcc...........',
    '......adfbfiigichhgkccdffeccifhhbfiiica.........',
    '.....aceegecjjkghhhhigdabchhglhhgikkeifa........',
    '....aceebdbcjjmhghhghhhihhhghhhflmmjbcde........',
    '...ccgicaafccmggihhlglhhihhlghhimhmjbachbdb.....',
    '...dfdilfbcedmiiiihglhhhlhhghggmjmmjabcehgdc....',
    '.aaelhhhhecdggkkfifhghhhghhligjmmkgmbddgebfec...',
    'aceifdjjilfmgikmmkkkggggihgkjmmjkkkgfiebaaafd...',
    'aefcdaacfllkhmmkmmmmmlcdbgkmmmjmmmmghcccggdaga..',
    'cidedcdbchlhkmjmkkkkmlcabgkkfkkemmmmgkhgediglba.',
    'hefcddcdcjlgjjmmmjmmfgdfdfimmmjmmjmmgllllgiihhdb',
    'fffcecdcablmmjmjmmjmgccbccimjmmmmmmmjhghllhifihd',
    'cdeffdebbblgggkjmmmmlcbabahmjjmjmgggkigmgllliiif',
    '..cddgeabdlkkkkghijmlccidahmjkhhikkkimhmggllldce',
    '....acdghllmmmmmkkkmlacidahmmkmkmmmjhklfccgllcbl',
    '......aachkmmmjjmiimhbacaagkmhmmmjjjhkiljbillcbe',
    '.......dfimkkmmmmikicaafcacikgmmmmkkhkmlhkgkgddl',
    '.......egmkhgikkkkmhfbcifaelmkkkkkhhimmgkhgemghl',
    '.......ceggkjmiggmmhhfimifglmmiggkjmkgibkjkfkdeg',
    '........chfdkggfjmmhkkkmkimlmjjmgggeegechdkkddhd',
    '.......bclcbddddihhkjjjmjmcefhgebbdcbcgaihimech.',
    '.......dfcaccbbabbbabbceecaabaabbaacdbcidggiei..',
    '.......bgddeedcaabaaceeiieebabbaabdeedcldgggf...',
    '.......bgkfbcddebabbfec.aceibbadeedcbedldgid....',
    '.......bchicbaccdbbbi.....cibacdccbbckeleik.....',
    '........chimjcbcebbic......cgbddbbbjmigdgef.....',
    '.........alhmmmkihic.......acigkmmmmhlcchee.....',
    '.........dllllllf............celllllldahged.....',
    '........adlhhlhh..............cehlhhlfclei......',
    '.......cdhhlllll..............cflllllhihei......',
    '.......aglhhhlid..............acflllhhllde......',
    '.......aclllhdc.................cdflllddib......',
  ] };
})();
(function () {
  const S = window.SPRITES = window.SPRITES || {};
  const PAL = { 'a': '#eee8ed:3', 'b': '#e4dbe5:3', 'c': '#b59ea0:2', 'd': '#54454f:1', 'e': '#dfd1dc:3', 'f': '#a1878d:2', 'g': '#6a5769:1', 'h': '#756971:1', 'i': '#302429:0', 'j': '#f3ddf5:3', 'k': '#d0bdc5:2', 'l': '#91706e:1', 'm': '#f0e1f2:3' };
  S['front_scientist'] = { w: 48, h: 48, pal: PAL, rows: [
    '.....................aab........................',
    '.....................bcde.......................',
    '.....................bfdgeaaba..................',
    '....................abaghgecic..................',
    '...................eehiiidiigia.................',
    '..................bbdbefgidgggda................',
    '.................bgiejklggggggdde...............',
    '.................bffbecghgggidggfk..............',
    '.................eheechgghgddighdf..............',
    '................aciechghgdidddggie..............',
    '................afichggdiildcfiidf..............',
    '.........abkke.bfidggdidfllccclil...............',
    '........bbfiigabddigddilfidlclga................',
    '........bliiidhaeghiimeebiklcdkc................',
    '........kidiiid....beddcmcckcldm................',
    '........eicekfd.....abchbkclldb.................',
    '.........adflda....amakhfchddc..................',
    '..........bddc....aakchfikcgckb.................',
    '.................abhdfjbhgcgifkb................',
    '................bkhlffhkbldghmdk...bffk.........',
    '................bfcjjkchfbfihhlg..bkddce........',
    '................kikjjjkgkckddhidaadiiidh........',
    '...............akigbemjjfgcdffidkadiiiii........',
    '..............bbhkfcccmbjbfdjjilffdfhhli........',
    '..............ecfjklfdjjjjjcfjdflckhecgh........',
    '..............cdbjkildmjjjjbckflglbfiiha........',
    '.............aehebkiikjjjjjjhffilcbaek..........',
    '.............kicdfkikmjjjjjjhfcicdc.............',
    '.............edhjeclghkjjjjjifcilhk.............',
    '..............kfgceccdgjjjjjgfcilc..............',
    '...............bfgjkgiifjjjjgfcihb..............',
    '................kdedekkfbjjjgfcic...............',
    '................ecdkjmjdejjjifcd................',
    '.................khejjbdejjjgfkd................',
    '.................ehjjjkdejjjgfefe...............',
    '.................ehkmecdjjjjgfelh...............',
    '.................bciiiidjjjjhfelg...............',
    '................aahejjbjjjjjfcbck...............',
    '................bcgjjjjjjjjcliefg...............',
    '................acljjjjjjjjhddlgh...............',
    '.................bchhcjjmbklggdik...............',
    '..................bfifhddddfhlfha...............',
    '...................ciccda..kglclhbb.............',
    '..................aclccla..khgclddk.............',
    '.................bbiglfda..ehdgiidde............',
    '.................bfidddia...efiiiiif............',
    '.................bciiiii.....akcffce............',
    '..................adiiif........................',
  ] };
})();
