// Imported pixel-for-pixel from prof_intro.png by tools/import_sheet.py
(function () {
  const S = window.SPRITES = window.SPRITES || {};
  const PAL = { 'a': '#000000:0', 'b': '#545454:1', 'c': '#f7f7f7:3', 'd': '#f8f8f8:3', 'e': '#040404:0', 'f': '#9e9e9e:2', 'g': '#535353:1', 'h': '#9d9d9d:2', 'i': '#555555:1', 'j': '#565656:1' };
  S['prof_intro'] = { w: 56, h: 56, pal: PAL, rows: [
    '....................ab...a..............................',
    '...................accaaadeaaab.........................',
    '....................accccccccccaab......................',
    '.................bbbcccffccccccccce.....................',
    '..................affcffffccccccccfb....................',
    '...................affgaabccabaabfca....................',
    '..................bhfbffcfacacccacfa....................',
    '...................afafcccfacccccaca....................',
    '....................aafccfcccccccafa....................',
    '....................baaacbcbcccaaaa.....................',
    '...................bccaaabfafaaaabca....................',
    '...................acacbcaccaacbcica....................',
    '...................acacbbacccabfcbca....................',
    '....................aabccbaccccccaa.....................',
    '.....................aaccffcccfcca......................',
    '......................acfaaaacbcb.......................',
    '.......................afbcccaba........................',
    '......................aaabcccbaaa.......................',
    '....................aafccaaaaacaca......................',
    '..................aaffccaaafcccaccaa....................',
    '.................aaaafccaaaaaaacccjcab..................',
    '.................acccaacaacccccaccbccci.................',
    '.................aaacccacccaaaaabbbccca.................',
    '................aabbaaaaaaabbbbabbcccccb................',
    '................acababaccabbbbbaccicccba................',
    '...............bccaacaccabbbbbbacccbcica................',
    '...............accaacacaaaabbbbaccbccaca................',
    '..............baaaaaacccccfabbbaccbccaccb...............',
    '..............accccaccccaaabbbbacjcccacca...............',
    '.............bcccccafccccabbaaaacbcccacca...............',
    '.............acccccaaacccaaaccaciccccacca...............',
    '.............accccccaaafacccccafbccccaccca..............',
    '..............acccccaaaaacccccafcccccaccca..............',
    '...............eaaaaffaaccccccafcccccafcca..............',
    '.................accaacaaaccaaaccccccaffa...............',
    '.................acccccabaaaabaccccccaffa...............',
    '.................acccccaaaccaaaccccbbafa................',
    '................icbicccabbaabbaaccbccca.................',
    '................acccgccabbabbbbaccbccca.................',
    '................acccbccabbabbbbaccbccca.................',
    '................acccbccabeabbbbaccbccca.................',
    '................acccbccabbbabbbaccbccca.................',
    '................acccbccabba.abbaccbccca.................',
    '................abccbccabba.abbaccbccba.................',
    '................acbbbccabba.abbaccbbbca.................',
    '................acccccabbfa.abbacccccca.................',
    '.................aacccabffa.abbaccccaa..................',
    '..................aaaaabfa...abaaaaaa...................',
    '..................abbbbffa...abbbbbba...................',
    '..................abbbfffa...abbbfffa...................',
    '..................abbbbffa...abffaaba...................',
    '.................abaaabbbba..abbbbbbba..................',
    '.................aaaaaaaaba.affaaaaaab..................',
    '.................afcccecca...aaafcccaa..................',
    '.................afffffaa.....affffcca..................',
    '..................aaaaa........aaaaaa...................',
  ] };
})();
