// Imported pixel-for-pixel from abbie_walk.png by tools/import_sheet.py
(function () {
  const S = window.SPRITES = window.SPRITES || {};
  const PAL = { 'a': '#333318:0', 'b': '#e26041:1', 'c': '#bdbdd0:2', 'd': '#ffffff:3', 'e': '#70683a:1', 'f': '#c7a358:2', 'g': '#414150:1', 'h': '#893324:1', 'i': '#f6b589:2', 'j': '#ffd0ac:3', 'k': '#d98968:2', 'l': '#000000:0', 'm': '#703a3a:1', 'n': '#481100:0', 'o': '#818189:2' };
  S['abbie_down_0'] = { w: 16, h: 21, pal: PAL, rows: [
    '...aaa....aaa...',
    '..abbbaaaabbba..',
    '..abaacbbcaaba..',
    '...acdbbbbdca...',
    '..abddbbbbddba..',
    '..abcddbbddcba..',
    '..abbbddddbbba..',
    '.aeebbbbbbbbeea.',
    '.afeghbbbbhgefa.',
    'aeffgijeejigffea',
    'aeegkiljjlikgeea',
    '.aelkkmiimkklea.',
    '..a.lmkkkkml.a..',
    '...lmnllllnml...',
    '..lddnbggbnddl..',
    '..lccmhbbhmccl..',
    '...lngccccgnl...',
    '....lkggggkl....',
    '....lhhllhhl....',
    '.....ll..ll.....',
    '................',
  ] };
  S['abbie_down_1'] = { w: 16, h: 21, pal: PAL, rows: [
    '................',
    '...aaa....aaa...',
    '..abbbaaaabbba..',
    '..abaacbbcaaba..',
    '...acdbbbbdca...',
    '..abddbbbbddba..',
    '..abcddbbddcba..',
    '..abbbddddbbba..',
    '.aeebbbbbbbbeea.',
    '.afeghbbbbhgefa.',
    'aeffgijeejigffea',
    'aeegkiljjlikgeea',
    '.aelkkmiimkklea.',
    '..aclmkkkkml.a..',
    '..lcmnllllnm....',
    '...lgnbgghddl...',
    '....gmhbbhccl...',
    '.....gccccgg....',
    '.....lkglll.....',
    '.....lhhl.......',
    '......ll........',
  ] };
  S['abbie_down_2'] = { w: 16, h: 21, pal: PAL, rows: [
    '................',
    '...aaa....aaa...',
    '..abbbaaaabbba..',
    '..abaacbbcaaba..',
    '...acdbbbbdca...',
    '..abddbbbbddba..',
    '..abcddbbddcba..',
    '..abbbddddbbba..',
    '.aeebbbbbbbbeea.',
    '.afeghbbbbhgefa.',
    'aeffgijeejigffea',
    'aeegkiljjlikgeea',
    '.aelkkmiimkklea.',
    '..a.lmkkkkmlca..',
    '....mnllllnmcl..',
    '...lddhggbngl...',
    '...lcchbbhmg....',
    '....ggccccg.....',
    '.....lllgkl.....',
    '.......lhhl.....',
    '........ll......',
  ] };
  S['abbie_left_0'] = { w: 16, h: 21, pal: PAL, rows: [
    '............aaa.',
    '.....aaaaa.abbba',
    '...aaddbbhhbhhha',
    '..ahbddcbbhhbbba',
    '..abbbddcbbhbbha',
    '.aebbbbcccccaaa.',
    '.aehbbbbbccbbg..',
    '.aeegabbbbbbba..',
    '.aeajjggbbbbga..',
    '..mjjjikaeeeea..',
    '..miilikafeea...',
    '...mkmkkgefea...',
    '....mkkgeeea....',
    '....nhgggll.....',
    '....nbgoogg.....',
    '....nbgddgjg....',
    '....ncgccnjg....',
    '.....lgllng.....',
    '.....lhhfl......',
    '......lll.......',
    '................',
  ] };
  S['abbie_left_1'] = { w: 16, h: 21, pal: PAL, rows: [
    '................',
    '............aaa.',
    '.....aaaaa.abbba',
    '...aaddbbhhbhhha',
    '..ahbddcbbhhbbba',
    '..abbbddcbbhbbha',
    '.aebbbbcccccaaa.',
    '.aehbbbbbccbbg..',
    '.aeegabbbbbbba..',
    '.aeajjggbbbbga..',
    '..mjjjikaeeeea..',
    '..miilikafeea...',
    '...mkmkkgefea...',
    '....mkkgeeea....',
    '....nhgggll.....',
    '....gddghgg.....',
    '...lgccghcgg....',
    '...llggccgkhl...',
    '....lllllhhnl...',
    '.........lll....',
    '................',
  ] };
  S['abbie_left_2'] = { w: 16, h: 21, pal: PAL, rows: [
    '................',
    '............aaa.',
    '.....aaaaa.abbba',
    '...aaddbbhhbhhha',
    '..ahbddcbbhhbbba',
    '..abbbddcbbhbbha',
    '.aebbbbcccccaaa.',
    '.aehbbbbbccbbg..',
    '.aeegabbbbbbba..',
    '.aeajjggbbbbga..',
    '..mjjjikaeeeea..',
    '..miilikafeea...',
    '...mkmkkgefea...',
    '....mkkgeeea....',
    '....nhgggll.....',
    '....nbhgddg.....',
    '....nchgccgg....',
    '...lbggcggjg....',
    '...lhbgllggl....',
    '....ll...ll.....',
    '................',
  ] };
  S['abbie_right_0'] = { w: 16, h: 21, pal: PAL, rows: [
    '.aaa............',
    'abbba.aaaaa.....',
    'ahhhbhhbbddaa...',
    'abbbhhbbcddbha..',
    'ahbbhbbcddbbba..',
    '.aaacccccbbbbea.',
    '..gbbccbbbbbhea.',
    '..abbbbbbbageea.',
    '..agbbbbggjjaea.',
    '..aeeeeakijjjm..',
    '...aeefakiliim..',
    '...aefegkkmkm...',
    '....aeeegkkm....',
    '.....llggghn....',
    '.....ggoogbn....',
    '....gjgddgbn....',
    '....gjnccgcn....',
    '.....gnllgl.....',
    '......lfhhl.....',
    '.......lll......',
    '................',
  ] };
  S['abbie_right_1'] = { w: 16, h: 21, pal: PAL, rows: [
    '................',
    '.aaa............',
    'abbba.aaaaa.....',
    'ahhhbhhbbddaa...',
    'abbbhhbbcddbha..',
    'ahbbhbbcddbbba..',
    '.aaacccccbbbbea.',
    '..gbbccbbbbbhea.',
    '..abbbbbbbageea.',
    '..agbbbbggjjaea.',
    '..aeeeeakijjjm..',
    '...aeefakiliim..',
    '...aefegkkmkm...',
    '....aeeegkkm....',
    '.....llggghn....',
    '.....gddghbn....',
    '....ggccghcn....',
    '....gjggcggbl...',
    '....lggllgbhl...',
    '.....ll...ll....',
    '................',
  ] };
  S['abbie_right_2'] = { w: 16, h: 21, pal: PAL, rows: [
    '................',
    '.aaa............',
    'abbba.aaaaa.....',
    'ahhhbhhbbddaa...',
    'abbbhhbbcddbha..',
    'ahbbhbbcddbbba..',
    '.aaacccccbbbbea.',
    '..gbbccbbbbbhea.',
    '..abbbbbbbageea.',
    '..agbbbbggjjaea.',
    '..aeeeeakijjjm..',
    '...aeefakiliim..',
    '...aefegkkmkm...',
    '....aeeegkkm....',
    '.....llggghn....',
    '.....gghgddg....',
    '....ggchgccgl...',
    '...lhkgccggll...',
    '...lnhhlllll....',
    '....lll.........',
    '................',
  ] };
  S['abbie_up_0'] = { w: 16, h: 21, pal: PAL, rows: [
    '...aaa....aaa...',
    '..abbbaaaabbba..',
    '..abbbhbbhbbba..',
    '...ahhhbbhhha...',
    '..ahccbhhbccha..',
    '..abcddbbddcba..',
    '..abbbddddbbba..',
    '.aegbbbbbbbbgea.',
    '.aeeegbbbbgeeea.',
    'aeeeeeeeeeeeeeea',
    'aeegeeeeeeeegeea',
    '.aelggeeeegglea.',
    '..a.lnllllnl.a..',
    '...lbghbbhgbl...',
    '..ldbggggggbdl..',
    '..lcggfjjfggcl..',
    '...lngjffjgnl...',
    '....lkggggkl....',
    '....lhhllhhl....',
    '.....ll..ll.....',
    '................',
  ] };
  S['abbie_up_1'] = { w: 16, h: 21, pal: PAL, rows: [
    '................',
    '...aaa....aaa...',
    '..abbbaaaabbba..',
    '..abbbhbbhbbba..',
    '...ahhhbbhhha...',
    '..ahccbhhbccha..',
    '..abcddbbddcba..',
    '..abbbddddbbba..',
    '.aegbbbbbbbbgea.',
    '.aeeegbbbbgeeea.',
    'aeeeeeeeeeeeeeea',
    'aeegeeeeeeeegeea',
    '.aelggeeeegglea.',
    '..allnllllnl.a..',
    '...lcghbbhgbl...',
    '...lcgggggghl...',
    '....ghgfjjfgdl..',
    '....ncgjffjncl..',
    '.....lkggglll...',
    '.....lhhll......',
    '......ll........',
  ] };
  S['abbie_up_2'] = { w: 16, h: 21, pal: PAL, rows: [
    '................',
    '...aaa....aaa...',
    '..abbbaaaabbba..',
    '..abbbhbbhbbba..',
    '...ahhhbbhhha...',
    '..ahccbhhbccha..',
    '..abcddbbddcba..',
    '..abbbddddbbba..',
    '.aegbbbbbbbbgea.',
    '.aeeegbbbbgeeea.',
    'aeeeeeeeeeeeeeea',
    'aeegeeeeeeeegeea',
    '.aelggeeeegglea.',
    '..a.lnllllnlla..',
    '...lbghbbhgcl...',
    '...lhggggggcl...',
    '..ldgfjjfghg....',
    '..lcnjffjgcn....',
    '...lllgggkl.....',
    '......llhhl.....',
    '........ll......',
  ] };
})();
