// Gen 3-style trainer battle sprites, imported pixel-for-pixel by tools/fit_sprite.py + tools/import_sheet.py.
// Loaded after sprites_trainers.js so these replace the hand-drawn versions of the same names.
// Each palette entry carries its Game Boy shade (:0-:3), which is what era 0 draws in Pallet Town.
(function () {
  const S = window.SPRITES = window.SPRITES || {};
  const PAL = { 'a': '#bd9473:2', 'b': '#e6c5a4:3', 'c': '#ffeed5:3', 'd': '#6a5a41:1', 'e': '#9c94ac:2', 'f': '#736a83:1', 'g': '#ded5ee:2', 'h': '#000000:0', 'i': '#eee6f6:2', 'j': '#9c836a:2', 'k': '#bdac8b:2', 'l': '#c58b39:2', 'm': '#decd9c:3', 'n': '#946a20:1' };
  S['front_grandpa'] = { w: 48, h: 48, pal: PAL, rows: [
    '...................abbaa........................',
    '.................abcccbbd.......................',
    '................accccccbef......................',
    '................ccccccccbae.....................',
    '...............accccccccbegh....................',
    '...............eiccciiigbaggf...................',
    '...............eigcciigebefggf..................',
    '...............hgiccebbbbfceg...................',
    '...............hbbccbbbbbabfgh..................',
    '...............ddaccddbbbdafe...................',
    '................dcccbccbdheh....................',
    '................ddbccbbbhff.....................',
    '.................dbdabdaf.......................',
    '..................dbbbdhhh......................',
    '..................hdhhajhjhhd...................',
    '................hdjddjkkldkmm...................',
    '................hknjkjjdldmmmd..................',
    '................hjljkjknldmmmj..................',
    '................hjnlddjlljkmmjd.................',
    '.................hlllllllnjkjkh.................',
    '..................dllllllldhjjjdd...............',
    '...................nlllllllnhjjjh...............',
    '...................dlllllllnhjjkk...............',
    '....................lllllllnddkkk...............',
    '....................llllnllnljjjd...............',
    '....................nllllnnlndhh................',
    '....................nnnnnnnnnh..................',
    '....................hdnnnndhh...................',
    '....................ddhhddnnd...................',
    '....................dddhnnnnn...................',
    '....................nddhnnnnn...................',
    '....................ndddnnnnn...................',
    '...................hndddnnnnn...................',
    '...................dndddnnnnn...................',
    '...................dnddddnnnn...................',
    '...................dddddhnnnn...................',
    '...................hdddhhnndn...................',
    '...................hdddhhnndn...................',
    '...................hdddhhndnn...................',
    '....................dddhdnnnn...................',
    '....................dddh.dnnd...................',
    '....................dddh.dnnd...................',
    '....................dddd.ddndh..................',
    '....................dddd.ddddh..................',
    '...................fhddd.hdddh..................',
    '..................hefhdh.hffhh..................',
    '..................hfffhhhfeefh..................',
    '..................hhhhh.hffffh..................',
  ] };
})();
(function () {
  const S = window.SPRITES = window.SPRITES || {};
  const PAL = { 'a': '#070707:0', 'b': '#736a83:1', 'c': '#524a62:1', 'd': '#7b6252:1', 'e': '#bd947b:2', 'f': '#f6dec5:3', 'g': '#d5b49c:2', 'h': '#9c94ac:2', 'i': '#ffffff:3', 'j': '#ded5ee:3', 'k': '#bdb4cd:2' };
  S['front_gymbro'] = { w: 48, h: 48, pal: PAL, rows: [
    '.......................aaaaa....................',
    '.....................aabbcccaa..................',
    '.....................abbbbcccb..................',
    '...............dda..acbbbccccba.................',
    '.............effggg.dgccgffgcca.................',
    '.............effeef.degfffcgbaa.................',
    '.............dgdddd.accfecggbdca................',
    '.............dggeg...agfffgbcgca................',
    '.............dfa.....defffffeaaa................',
    '.............dfa.....aggfefffca.................',
    '............effa......adeffeaa..................',
    '............dfga......dffadaaa..................',
    '...........efffdaadffdhgffgciidaa...............',
    '...........dfffdgfffdiifffciiifffd..............',
    '...........agffeggghiiiiiihiiiffff..............',
    '.............agggggaiiieiiiiidffefffd...........',
    '..............dadggaiiiddhiijdffggega...........',
    '................aaaajiideijjhjggggggg...........',
    '...................ahjjdiihjjjaaggggg...........',
    '....................hiiiiiiijj...afgf...........',
    '....................aiiiiiiiij...affd...........',
    '....................ajiiiiiiih..dffga...........',
    '....................aijjiiiija.ddffd............',
    '....................ajjjiiidffeggea.............',
    '....................aajiiidfggfgaa..............',
    '....................hjahhhagfeaa................',
    '...................ajikkhjiiaaa.................',
    '...................aiijjhiiiii..................',
    '...................aiijjhjiiiia.................',
    '...................hiijjaiiiiih.................',
    '...................jijjjjaiiiiia................',
    '...................jjjjja.jiiiiia...............',
    '...................ahjjja.kiiiiia...............',
    '...................ffgdaa.hjihhaa...............',
    '...................ffffa...afffa................',
    '...................ffffa...dfffa................',
    '...................ffed....dfffd................',
    '...................gfgg....afffgd...............',
    '...................dggg.....dfgga...............',
    '...................dggg.....dggga...............',
    '...................agg.......aggga..............',
    '...................agga.......ggga..............',
    '...................agga.......egga..............',
    '...................agga.......agga..............',
    '..................aaega.......agga..............',
    '...............acccbcca.......abbc..............',
    '...............aaaccaaa......acccb..............',
    '...............aaaaaa........aaaaa..............',
  ] };
})();
(function () {
  const S = window.SPRITES = window.SPRITES || {};
  const PAL = { 'a': '#35313e:1', 'b': '#742320:1', 'c': '#000000:0', 'd': '#d47363:2', 'e': '#d45742:1', 'f': '#ad3f30:1', 'g': '#cc8c7c:2', 'h': '#93615d:1', 'i': '#785850:1', 'j': '#f8f8f8:3', 'k': '#793e3f:1', 'l': '#646464:1', 'm': '#b9b9b9:2', 'n': '#2a3950:1', 'o': '#e88060:2', 'p': '#a0b0b8:2', 'q': '#101a2a:0', 'r': '#c83850:1', 's': '#ffffff:3', 't': '#0d131b:0', 'u': '#8d704a:1', 'v': '#d0d298:3', 'w': '#b69e64:2' };
  S['front_influencer'] = { w: 48, h: 48, pal: PAL, rows: [
    '.............................aaa................',
    '........................bbbbcaac................',
    '......................ddddddebcbac..............',
    '.....................ddddddeebfca...............',
    '....................bddedeeefeef................',
    '....................ceddeebbddddb...............',
    '....................ebbbcgghbdddb...............',
    '....................beiaggaabeeeb...............',
    '.....................ijcgajchbee................',
    '.....................chgggghhbb.................',
    '....................fchkgggglc..................',
    '...................ccfchjjkhcfc.................',
    '..................iccmfchhhcffnc................',
    '.................iigiocfpqqqfnnc................',
    '.................igirrcccmmnncc.................',
    '.................kggijcsnsssnt..................',
    '...............ccggijcmnnnsssqt.................',
    '...............cchkccmsnnnqsnnn.................',
    '...............cbcctcqqnnnqtnnnq................',
    '..............tnffbkfbctnnqnqqt.................',
    '..............qnnqckfebnctnnnnc.................',
    '..............qnqccifbqnnnnnnc..................',
    '..............cqqc.ccbqqqnnnc...................',
    '...............cc..cuccqqqqc....................',
    '...................cupvccttc....................',
    '..................cupvvvwwucc...................',
    '..................cupccccccuc...................',
    '..................ccpvvwwuuuc...................',
    '..................cbccccccccc...................',
    '..................cbtbtnnenn....................',
    '..................cbtbnnnenn....................',
    '..................cbttenneee....................',
    '..................cttttnnnnnc...................',
    '..................cttttcnnnnc...................',
    '..................cttttcnnnnc...................',
    '..................ccctttccccc...................',
    '...................chhcc.cggc...................',
    '...................chhhc..cgc...................',
    '....................chhc..chhc..................',
    '....................ckhc..chhc..................',
    '....................chhh..ckhkc.................',
    '...................chnqc..chhhc.................',
    '...................ccqqc.cccccc.................',
    '..................ccnnqc..cqqqc.................',
    '.................qqwsmqc..cmmqc.................',
    '................qnnnecqc..cqqc..................',
    '................cnnceee..cqnnqc.................',
    '..........................cccc..................',
  ] };
})();
(function () {
  const S = window.SPRITES = window.SPRITES || {};
  const PAL = { 'a': '#684848:1', 'b': '#c07808:1', 'c': '#000000:0', 'd': '#d8a048:2', 'e': '#c08868:2', 'f': '#e8b090:2', 'g': '#f8d8c8:3', 'h': '#705080:2', 'i': '#9868a8:2', 'j': '#304050:1', 'k': '#687880:1', 'l': '#c0c8b0:3', 'm': '#f8f8f8:3', 'n': '#c888f8:2' };
  S['front_rival'] = { w: 48, h: 48, pal: PAL, rows: [
    '.........................a......a...............',
    '.........................b....cba...............',
    '........................cda.cbdd................',
    '........................adcbdddb................',
    '.....................cdaddbbbbbbbbba............',
    '.....................cdddddbbbbbbbc.............',
    '......................adddddddbbbbbbba..........',
    '......................cdddbbdddbabbbc...........',
    '.......................addabbaabbabb............',
    '.......................ccaeadbeedbab............',
    '......................cdfaecabecaeaa............',
    '.....................cdcffgceeeffaa.............',
    '...........cgc..........caegggefc...............',
    '..........caahcceee......cageaffc...............',
    '.........cffefhihggeeccccjkkaefa................',
    '.........cefaeeicgggfeckkjkkecc.................',
    '.............ca...ccefjkkkkkejjc................',
    '.....................jkjkkkkjjkc................',
    '.....................cccjkkkkkjk................',
    '........................cjkkkkjk................',
    '.........................cjjkkkkc...............',
    '.........................cjjjjjkj...............',
    '.........................cjjjkkjc...............',
    '..........................jjjjjkc...............',
    '..........................cjjjjjjc..cfa.........',
    '.........................kkkllkkcckcfeg.........',
    '........................kmmmmlklccceefe.........',
    '........................lllllkkjjjceec..........',
    '........................mmmmllcjjjc.............',
    '........................lmmmlkhchhhc............',
    '........................ckkkkchchhhc............',
    '........................ciiiiihhhhh.............',
    '........................nnhnnichhhhh............',
    '........................nninnhchhhhh............',
    '........................hhnnncchhhhh............',
    '........................nnnnic.chhhh............',
    '........................innnh..chhhhc...........',
    '.......................hinni....hhhhc...........',
    '.......................hinni....hhhic...........',
    '......................hihii....chhii............',
    '.....................hiiiic....chhii............',
    '.....................hihihc....chhii............',
    '.....................ihiiic....chhhh............',
    '.....................ihihc......hhhhc...........',
    '.....................ihhhc......hhhic...........',
    '.....................hhhc.......chjjkc..........',
    '.....................jjkcc.......ccjjjc.........',
    '.....................jjjjc.........ccc..........',
  ] };
})();
(function () {
  const S = window.SPRITES = window.SPRITES || {};
  const PAL = { 'a': '#ead5e8:3', 'b': '#bb9fa4:2', 'c': '#c3b7c3:2', 'd': '#937f87:2', 'e': '#715f6b:1', 'f': '#50434f:1', 'g': '#80727f:1', 'h': '#f2ddf2:3', 'i': '#f6e6f7:3', 'j': '#36282e:0', 'k': '#655160:1', 'l': '#af8482:2', 'm': '#dfc1cd:3' };
  S['front_cheeselover'] = { w: 48, h: 48, pal: PAL, rows: [
    '..........................abc...................',
    '.........................bdefd..................',
    '.......................fgdbhij..................',
    '.....................cebhiihide.................',
    '....................cdcaihabfckff...............',
    '...................cfaiiiheeljcmmfe.............',
    '..................cfhhihhcgfeljmmimg............',
    '..................gaaihhhdkljljjfhmj............',
    '.................cehhihhceelkbmffcb.............',
    '.................fahhhiilfmhahmjfcf.............',
    '.................jhaiihfjbahhhmjjbcf............',
    '.................jhhhidjjbahimjbjfj.............',
    '.................jaihiklbjbmhgjbj...............',
    '.................jchiigebfdemakmd...............',
    '................begihihfmdhhdbdab...............',
    '................jmdacbhcdmhhkkgm....hbd.........',
    '...............kdabhbdhhjbmhfbak...debbg........',
    '..............ckmdahabckfjdabmf...eccaacd.......',
    '..............bkabhihgdgfceegj...dchckddk.......',
    '.............mfadaaiaejgghhkjc...fimfgjj........',
    '............gedmmahhbebjihhhdjedbbae.edb........',
    '...........edbmbhhimlllkicchicffkmak............',
    '...........jamdhhhadllllkagbhhcfcik.............',
    '.........ejbacahhagblllbbeakbhhhiag.............',
    '........ggmimdhhadblllljceekjcaiif..............',
    '........dgmhbahablllllkceefekjbamg..............',
    '........aeccdhadllbbldcaflggekjek...............',
    '.......mecdgahcklbmmcdcebkkbeeej................',
    '........ekefahckllmmddijlffddgef................',
    '...........ajahmmbmldhdbgfcbgkeefc..............',
    '............jmblbmmdgiecbjgbbekfkd..............',
    '............kdffdcdeidbhdjgkggfjjjb.............',
    '................gg.iaecafffkchakeagc............',
    '...................mebhbbmfdahhmecaf............',
    '..................aklihfiimkbhhamkcdb...........',
    '...............bffadflmcbiimfbaihckcf...........',
    '..............cjbkfcfkjddiiicflahhmgbb..........',
    '..............bjeej.becfiiadjljbhhmjdf..........',
    '...............fbb..akjdbfjlllefahhcj...........',
    '....................djeffeggfggmahafk...........',
    '...................mfeeejjjklmahakg.............',
    '...................bjkjbcgkmamacf...............',
    '...................cjejjjfmmafj.................',
    '...................cffjjbmbk....................',
    '....................bjjjbgj.....................',
    '.....................efjgce.....................',
    '.......................jjgek....................',
    '........................jjij....................',
  ] };
})();
(function () {
  const S = window.SPRITES = window.SPRITES || {};
  const PAL = { 'a': '#8f7072:1', 'b': '#d3a197:2', 'c': '#825e5a:1', 'd': '#37292f:0', 'e': '#614f56:1', 'f': '#cfbec9:2', 'g': '#191415:0', 'h': '#efd8ea:3', 'i': '#f3e1f4:3', 'j': '#ecc8cf:3', 'k': '#47363d:0', 'l': '#a3898c:2', 'm': '#ca8f7c:2' };
  S['front_bbqdad'] = { w: 48, h: 43, pal: PAL, rows: [
    '....................ab....bc....................',
    '....................deb..feg....................',
    '.................hijdgebbcgg..hf................',
    '................fkakgggdggggdcdgk...............',
    '................fgggggggggggggggd...............',
    '..............aalgggggggggggggggc...............',
    '..............ldgggggggggggggggdlf..............',
    '..............jkgggggggggggggggggd..............',
    '...............ldgggggggggggggggda..............',
    '...............jcgggggggggggggggea..............',
    '..............adggccgggaadggelcdda..............',
    '............iaeacdbjffijhffffjbdalea............',
    '...........fklfbekdajhhhhhhjlkeebhflkf..........',
    '..........leliiaemkdkeaaalekgkaceihhlk..........',
    '..........gagljemckagkmmmfkgaecmklfada..........',
    '..........akecffcaebaaembacajaacclbeed..........',
    '..........dmjklifekmajfmjljhmeelkhlkjba.........',
    '.........cljhecjjleambbafhbmdlakjjceihk.........',
    '.......hhehhjaklhjadamlggafelllahlklhiajhh......',
    '......fedejjmllchhjcfldmmeekfajhfcmajjbddef.....',
    '.....ldememaabbkhiifefallcahefiifdmlaamemcdl....',
    '..faedggeammmcedbhhjeffcmefhehiifgdcmmmceggdef..',
    '..lelackgcmbmlekbhihlefkckfkbiiifkdlmmmcgdcbllf.',
    '.lgeclmlkdbfaifkabjhikmeklbcmmjjlefhajbkelameeg.',
    'idcgkkdladmlelkckabjjaacemkmmmmakaeleamdaldkdge.',
    'hdaemkkckdachammmklaccgkkckccaaeiiibfeadkckkbel.',
    '.kdabckleklllemmbbmcdgggggggdafjiifclllkeadcjak.',
    '.fkddklgkfdlfmkbjhjjmmaekaalfhiiifkmmaefkgfekdk.',
    '...lgbldlicjhjbaehiijbbkkdmmbihjkabjjbcildfbg...',
    '.........lbiihhbaejhifkmmlkmmmmkmjiiijb....k....',
    '........fehiiiiimceblkkkkkkdcaechhiiihjef.......',
    '........lahiiiiibmacdee....lekamhiiiiihla.......',
    '.........lfhiiiijbmck.......bdamiiiiiiife.......',
    '........iecfiiiijmc...........ecbhiiiiilk.......',
    '.......fkcjjihjfmc.............emjiiiiilc.......',
    '.......caefflbadee..............cbjhiijeblf.....',
    '.......defaddklhlf.............fkmmbjjbflld.....',
    '.......llfdmllhhfa............aecaeamake........',
    '......ieeeambhfel.............acfedkdalaf.......',
    '......lmmlmmbl....................aklmjbc.......',
    '.......edjjjk......................lcamjfcf.....',
    '..................................fabdmaajd.....',
    '...................................ealcaal......',
  ] };
})();
(function () {
  const S = window.SPRITES = window.SPRITES || {};
  const PAL = { 'a': '#ddc6d8:3', 'b': '#cdb4c2:2', 'c': '#ab94a0:2', 'd': '#a47f7f:2', 'e': '#5d474b:1', 'f': '#3f2f35:0', 'g': '#796771:1', 'h': '#ecd7ea:3', 'i': '#f4e0f6:3', 'j': '#e09a7a:2', 'k': '#976b67:1', 'l': '#23191d:0', 'm': '#d89172:2' };
  S['front_chef'] = { w: 48, h: 44, pal: PAL, rows: [
    '.....................abbbba.....................',
    '...................acdefffgca...................',
    '..................ccdacbacadcd..................',
    '.................adahhdihcbihc..................',
    '.................ddcgggcggggdce.................',
    '...............ieejaabaaaaaaajk.................',
    '..............dehabbellffllfbbbgd...............',
    '..............cbceledkfdmegcklfca...............',
    '..............cgflgbfeekkeeebdlfg...............',
    '..............bbcfbgggdaacgggaegd...............',
    '..............gcecichiicdhhhcibebe..............',
    '..............ddfkhglecddcgleidfc...............',
    '...........cddagfechgccddccgabgfg...............',
    '.......cghggeeeaffedbacggcabggffhgggg...........',
    '......adcecajjdeffffgebihbffffffekkkdeg.........',
    '......cdhbhajjmffffefffefffefffglmmbhbbc........',
    '....aegaiigaajeegfflelffeffleffemfjbiihfh.......',
    '....gcglghacbmggggfelffflffeffemjmmbihhcfec.....',
    '...clffffdaceekkgggfefffefflgejmjkechbbechgd....',
    '..cggcbjklgdeekmmkdkefeegfekjjmjkdkeggciiiigc...',
    '.dghciiagllkfjmddjjmmlbciekjmmjmdmmefbbaeecie...',
    '.ebcbachaflfkjjmkkkkdlhiiekkgdkdmjjmedfeccgfl...',
    'fdgabchcablejjjjmjmmgebgcgemjjjmmjmjelllleegffb.',
    'gggadacaihlmjjmjmjjmeahhbagmjmmjmmjmjfefllfeggf.',
    '..cggbciihleeekjmjmmlaiiiifjjjmjmeeekeemelllegg.',
    '....cecihblkkkkefkjmfaagbifmjkffkkkkgdfdeelllcbc',
    '......beflljmjmddkdmliagcifdmkdkmjmjfklgbaellaif',
    '........hfdmjjjjjekmfiihiiedmfjjjjjjfkelchellaic',
    '........ggdkkmjmmkkgbiigaihedejjmmkkfdmlfdekecbl',
    '........edkfeekkkdmfghaegiclmkkkkkffgmmekfedmefl',
    '........ceedjdeeedjffggmegelmmkeedjmkekhkjkgdcd.',
    '.........fgckfegjmjfkkkmkedlmjjdefeccedafbkkccf.',
    '.........lbibccbgffdbjjmjmbcgfeciichibehefkmda..',
    '........gbibaiiiiihiiiaccaiiiiiiiiiabhaecfegc...',
    '........ecccccaiiiiihdc.gddhiihiihccccalcfee....',
    '........edghabcciiihg.....cgihibccbaidclceg.....',
    '........bfgbhiaaciiig......ehibcbaihbddldg......',
    '.........fgdjbhhdhhg........ehcchhhbmgfced......',
    '..........lfmmdkgfe..........gekdmmmflaafd......',
    '..........llllll..............cllllllbifec......',
    '.........clfflff...............cflfflghlc.......',
    '........cfflllll...............dllflffgfc.......',
    '........elfffl..................glllffllc.......',
    '.........lll......................glll.c........',
  ] };
})();
(function () {
  const S = window.SPRITES = window.SPRITES || {};
  const PAL = { 'a': '#efe0f2:3', 'b': '#b1a6b2:2', 'c': '#534047:1', 'd': '#928593:2', 'e': '#423941:0', 'f': '#645567:1', 'g': '#7d6060:1', 'h': '#e7d2e4:3', 'i': '#2b2024:0', 'j': '#f6e0f8:3', 'k': '#d7aca8:2', 'l': '#8a7173:1', 'm': '#b58b88:2' };
  S['front_scientist'] = { w: 48, h: 48, pal: PAL, rows: [
    '.....................a..........................',
    '.....................bc.........................',
    '.....................def........................',
    '.....................aggf.be....................',
    '...................hfiiieiefe...................',
    '..................hchhdfecfffc..................',
    '..................ihjklfffffffc.................',
    '.................ddhhmflfffecffd................',
    '.................lhhmlffffcceffc................',
    '................behmgffffiegcffe................',
    '................demgffeielcmmiic................',
    '..........bb...deffffefmlmmmkge.................',
    '.........diif..ceifcceddiclklg..................',
    '........diiiel....eijhhhekgkek..................',
    '........iciiec.....hcebammkmlc..................',
    '........ebhkme.......blhkmllc...................',
    '.........fdlg........hgmbgce....................',
    '...................kdldikmgbb...................',
    '..................ledjhggmgedb..................',
    '................bllddlbhlcglac..................',
    '...............adbjjbbldhdilllf...keeb..........',
    '...............bekjajbfbbbcclic..fiiicl.........',
    '...............hefhhajjdfbfddic..ciiiii.........',
    '..............hlbdkmbahjhdcaaild.cdgggi.........',
    '..............bdaklmcjjjjabdafml..ghkg..........',
    '..............ehjkigcaaaajhbkmlg..deil..........',
    '.............hlhhkiekjjjjjjgddelb...............',
    '.............ibcdkibajjjjjjgdbemc...............',
    '.............clahkmggbjjjjjidbelg...............',
    '..............dfbhkmgfjjajjfdbil................',
    '...............dfjkgiidjjjjfdbi.................',
    '...............bchchkkdhjjjfdbi.................',
    '................bchaaaehjjjidbc.................',
    '.................lhjjhehjjjfdbf.................',
    '.................ljjjhehjjjfdhd.................',
    '.................lhahkcjajjfdhl.................',
    '.................beeeicjjjjfdhg.................',
    '................alhaahjjjjadbhm.................',
    '................bfaajajajjblehd.................',
    '................bljjjajjajlcclf.................',
    '.................bllbjajhkgfgce.................',
    '...................idlccccmflml.................',
    '...................immc....fgmgg................',
    '..................blmmg....fgmmccb..............',
    '.................higgmc....lefiicc..............',
    '.................diccei......iiiiid.............',
    '.................bieiii.........................',
    '..................ciii..........................',
  ] };
})();
