// Imported pixel-for-pixel from prof_intro.png by tools/import_sheet.py
(function () {
  const S = window.SPRITES = window.SPRITES || {};
  const PAL = { 'a': '#f7f7f7:3', 'b': '#000000:0', 'c': '#545454:1', 'd': '#555555:1', 'e': '#9e9e9e:2', 'f': '#f6f6f6:3', 'g': '#f8f8f8:3', 'h': '#4b4b4b:1', 'i': '#040404:0', 'j': '#111111:0' };
  S['prof_intro'] = { w: 56, h: 56, pal: PAL, rows: [
    '............aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa............',
    '............aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa............',
    '............aaaaaaaaabcaaabaaaaaaaaaaaaaaaaa............',
    '............aaaaaaaabaabbbabbbcdaaaaaaaaaaaa............',
    '............aaaaaaaaabaaaaaaaaaabbaaaaaaaaaa............',
    '............aaaaaacccaaeeeaaaaaaaafaaaaaaaaa............',
    '............aaaaaaabeeaeeeeaaaaaaaecaaaaaaaa............',
    '............aaaaaaaabeecbbcaababbcabaaaaaaaa............',
    '............aaaaaaaaeebeaaebaaaaaaabaaaaaaaa............',
    '............aaaaaaaabebeaaaaaaaaaaabaaaaaaaa............',
    '............aaaaaaaaabbeaaaaaaaaabebaaaaaaaa............',
    '............aaaaaaaacabbbdcababbbbbbaaaaaaaa............',
    '............aaaaaaaababacabaabbgccabaaaaaaaa............',
    '............aaaaaaaababaccbaabbcecabaaaaaaaa............',
    '............aaaaaaaaabbcaacaaaaaaabaaaaaaaaa............',
    '............aaaaaaaaaabbaaeaaaaaaaaaaaaaaaaa............',
    '............aaaaaaaaaaabaebbbaacacaaaaaaaaaa............',
    '............aaaaaaaaaaaaeecaaaccbaaaaaaaaaaa............',
    '............aaaaaaaaaaabbbcaaacbbaaaaaaaaaaa............',
    '............aaaaaaaaabbeahbbbbbabaaaaaaaaaaa............',
    '............aaaaaaabbeeaabbbeaaababbaaaaaaaa............',
    '............aaaaaabbbbeaabbbbbbbaacabcaaaaaa............',
    '............aaaaaabaaabbabbaaaagbacaaadaaaaa............',
    '............aaaaaabbbaaabaabbbbbbccaaabaaaaa............',
    '............aaaaabbccbbbbbbcccccbcaaaaacaaaa............',
    '............aaaaababcbcbaabcccccbadaaacbaaaa............',
    '............aaaacaabbabaabccccccbaacadabaaaa............',
    '............aaaabaabbababbbbccccbacaababaaaa............',
    '............aaacbbbbbbaaaaabdcccbacaabaacaaa............',
    '............aaabaaaabaaaabbccccbbaaaabaabaaa............',
    '............aacaaaaabeaaaabcbbbbaaaaabaabaaa............',
    '............aabaaaaabbbaabbbaabbaaaaabaaaaaa............',
    '............aaaaaaaaabbbbbaaaaabeaaaabaaabaa............',
    '............aaaaibbbbjbbbaaaaaabeaaaabeaabaa............',
    '............aaaaaabaabbbbbaaabbbaaaaabeebaaa............',
    '............aaaaaabaaaaabbbbbbbbaaaaabeebaaa............',
    '............aaaaaabaaaaabbbabbbbaaaccbebaaaa............',
    '............aaaaadfcaaaabcbbbcbbaacaaabaaaaa............',
    '............aaaaabaaacaabccbcccbbacaaabaaaaa............',
    '............aaaaabaaacaabccbccccbacaaabaaaaa............',
    '............aaaaabaaacaabcbbccccbacaaabaaaaa............',
    '............aaaaabaaacaabcccbcccbacaaabaaaaa............',
    '............aaaaabaaacaabccbacccbacaaabaaaaa............',
    '............aaaaabcaacaabccbbbccbacaacbaaaaa............',
    '............aaaaabacccaabccbabccbacccabaaaaa............',
    '............aaaaabaaaaabccebabccbaaaaabaaaaa............',
    '............aaaaaabbaaabceeaacccbaaaibaaaaaa............',
    '............aaaaaaabbbbbcebaaaccbbbbbaaaaaaa............',
    '............aaaaaaabcccceebaaabcccccbaaaaaaa............',
    '............aaaaaaabccceeebaaabccceebaaaaaaa............',
    '............aaaaaaabcccceebaabbcebbccaaaaaaa............',
    '............aaaaaabbbbbccccbabeccccccbaaaaaa............',
    '............aaaaaabbbbbbbbcaaiebbbbbbbaaaaaa............',
    '............aaaaaabeaaaiaaaaaabbeeaaabaaaaaa............',
    '............aaaaaabeeeeebaaaaaabeeeaaaaaaaaa............',
    '............aaaaaaaaabbaaaaaaaaaabbabaaaaaaa............',
  ] };
})();
