// OUTDOOR 16x16 tile sprites: grass/path/water/tree/props and Gen1-style house pieces.
// Original Gen2/3-inspired pixel art (no copyrighted assets). See ART_SPEC.md for the format
// and js/tiles.js for how these tile ids are wired into the map legend.
(function () {
  const S = window.SPRITES = window.SPRITES || {};
  S['tile_grass'] = {
    w: 16, h: 16,
    pal: { 'a': '#8cc873:3', 'b': '#5a9648:1', 'c': '#c0f0a0:2' },
    rows: [
      'aaaaaaaaaaaaaaaa',
      'aaaaaaaaaaaaaaaa',
      'aaaaaaaaaaaaaaca',
      'aaaabaaaacaaaaaa',
      'aaabaaaaaaaaaaaa',
      'aaaaaaaaaaaabaaa',
      'aaaaaaaaaaabaaaa',
      'aaaaaaaaaaaaaaaa',
      'aaaaaaaaaaaaaaba',
      'aaabaaaaaaaaabaa',
      'aabaaaaaaaaaaaaa',
      'aaaaaaaabaaaaaaa',
      'aaaaaaabaaaaaaaa',
      'aaaaaaaaaaaaaaaa',
      'aaaaacaaaaaaaaaa',
      'aaaaaaaaaaaaaaaa',
    ]
  };
  S['tile_tallgrass'] = {
    w: 16, h: 16,
    pal: { 'a': '#8cc873:3', 'e': '#3f7a3a:1', 'f': '#25501f:0', 'h': '#5fae52:2' },
    rows: [
      'aaaaaaaaaaaaaaaa',
      'aaaaaaaaaaaaaaaa',
      'aaaaaaaaaaaaaaaa',
      'aaaaaaaaaaaaaaaa',
      'aaaaaaaaaaaaaaaa',
      'eaaaeaaaeaaaeaaa',
      'heaaheaaheaaheaa',
      'eeeaeeeaeeeaeeea',
      'eeheeeheeeheeehe',
      'eeeeeeeeeeeeeeee',
      'eeeeeeeeeeeeeeee',
      'eeeeeeeeeeeeeeee',
      'eeeeeeeeeeeeeeee',
      'eeeeeeeeeeeeeeee',
      'eeeeeeeeeeeeeeee',
      'ffffffffffffffff',
    ]
  };
  S['tile_path'] = {
    w: 16, h: 16,
    pal: { 'a': '#dcbb7c:2', 'b': '#b2905a:1', 'c': '#efd9a6:2' },
    rows: [
      'aaaaaaaaaaaaaaaa',
      'aaaaaaaaaaaaaaaa',
      'aaaaaacaaaaaaaaa',
      'aaabaaaaaaaaaaaa',
      'aaaaaaaaaaaabaaa',
      'aaaaaaaaaaaaaaaa',
      'aaaaaaaaabaaaaaa',
      'aaaaaaaaaaaaaaaa',
      'aaaaaaaaaaaaaaaa',
      'aaaaaaabaaaaaaaa',
      'aaaaaaaaaaaaaaaa',
      'aaaaaaaaaaacaaaa',
      'aabaaaaaaaaaaaaa',
      'aaaaaaaaaaaaabaa',
      'aaaaaaaaaaaaaaaa',
      'aaaaaaaaaaaaaaaa',
    ]
  };
  S['tile_pavement'] = {
    w: 16, h: 16,
    pal: { 'a': '#c9c9d2:3', 'b': '#a3a3ae:2', 'c': '#dcdce4:3' },
    rows: [
      'aaaaaaaabaaaaaaa',
      'aaaaaaaabaaaaaaa',
      'aaaaaaaabaaaaaaa',
      'aaacaaaabaaacaaa',
      'aaaaaaaabaaaaaaa',
      'aaaaaaaabaaaaaaa',
      'aaaaaaaabaaaaaaa',
      'aaaaaaaabaaaaaaa',
      'bbbbbbbbbbbbbbbb',
      'aaaaaaaabaaaaaaa',
      'aaaaaaaabaaaaaaa',
      'aaaaaaaabaaaaaaa',
      'aaacaaaabaaacaaa',
      'aaaaaaaabaaaaaaa',
      'aaaaaaaabaaaaaaa',
      'aaaaaaaabaaaaaaa',
    ]
  };
  S['tile_tree'] = {
    w: 16, h: 16,
    pal: { 'g': '#8cc873:3', 'o': '#1c3a1c:0', 'd': '#2f6b34:1', 'm': '#5fae52:2', 'l': '#a8e888:3', 'u': '#5c3a20:0', 't': '#7a5030:1' },
    rows: [
      'gggggooooogggggg',
      'gggoommdddoogggg',
      'ggommmmdddddoggg',
      'gommlmmmdddddogg',
      'ommmmlmmddddddog',
      'ommmmmmmmdddddog',
      'ommmmmmmmmddddog',
      'ommmmmmmmmddddog',
      'gommmmmmmmmddogg',
      'ggommmmmmmmdoggg',
      'gggoommmmmoogggg',
      'gggggooooogggggg',
      'gggggguttugggggg',
      'gggggguttugggggg',
      'gggggguttugggggg',
      'gggggguuuugggggg',
    ]
  };
  S['tile_water_0'] = {
    w: 16, h: 16,
    pal: { 'a': '#4f8ad0:2', 'c': '#a8d8fb:3' },
    rows: [
      'aaaaaaaaaaaaaaaa',
      'aaaaaaaaaaaaaaaa',
      'aaaaaaaaaaaaaaaa',
      'accccaaaaccccaaa',
      'aaaaaaaaaaaaaaaa',
      'aaaaaaaaaaaaaaaa',
      'aaaaaaaaaaaaaaaa',
      'aaaaaaaaaaaaaaaa',
      'caaaaccccaaaaccc',
      'aaaaaaaaaaaaaaaa',
      'aaaaaaaaaaaaaaaa',
      'aaaaaaaaaaaaaaaa',
      'ccccaaaaccccaaaa',
      'aaaaaaaaaaaaaaaa',
      'aaaaaaaaaaaaaaaa',
      'aaaaaaaaaaaaaaaa',
    ]
  };
  S['tile_water_1'] = {
    w: 16, h: 16,
    pal: { 'a': '#4f8ad0:2', 'c': '#a8d8fb:3' },
    rows: [
      'aaaaaaaaaaaaaaaa',
      'aaaaaaaaaaaaaaaa',
      'aaaaaaaaaaaaaaaa',
      'aaaccccaaaacccca',
      'aaaaaaaaaaaaaaaa',
      'aaaaaaaaaaaaaaaa',
      'aaaaaaaaaaaaaaaa',
      'aaaaaaaaaaaaaaaa',
      'cccaaaaccccaaaac',
      'aaaaaaaaaaaaaaaa',
      'aaaaaaaaaaaaaaaa',
      'aaaaaaaaaaaaaaaa',
      'aaccccaaaaccccaa',
      'aaaaaaaaaaaaaaaa',
      'aaaaaaaaaaaaaaaa',
      'aaaaaaaaaaaaaaaa',
    ]
  };
  S['tile_flower_0'] = {
    w: 16, h: 16,
    pal: { 'a': '#8cc873:3', 'b': '#5a9648:1', 'y': '#f6d84a:3', 'r': '#e0504a:1', 'p': '#f08ab0:3', 'k': '#2f5424:0' },
    rows: [
      'aaaaaaaaaaaaaaaa',
      'aaaaaaaaaaaaaaaa',
      'aaaaaaaaaaaaaaaa',
      'aaaabaaaaaayaaaa',
      'aaabaaaaaayyyaaa',
      'aaaaaaaaaaaybaaa',
      'aaaaaaaaaaakaaaa',
      'aaaaaaaaaaaaaaaa',
      'aaaaraaaaaaaaaba',
      'aaaryraaaaaaabaa',
      'aabaraaaaaaaaaaa',
      'aaaakaaabaaapaaa',
      'aaaaaaabaaapypaa',
      'aaaaaaaaaaaapaaa',
      'aaaaaaaaaaaakaaa',
      'aaaaaaaaaaaaaaaa',
    ]
  };
  S['tile_flower_1'] = {
    w: 16, h: 16,
    pal: { 'a': '#8cc873:3', 'b': '#5a9648:1', 'y': '#f6d84a:3', 'r': '#e0504a:1', 'p': '#f08ab0:3', 'k': '#2f5424:0' },
    rows: [
      'aaaaaaaaaaaaaaaa',
      'aaaaaaaaaaaaaaaa',
      'aaaaaaaaaaaaaaaa',
      'aaaabaaaaayayaaa',
      'aaabaaaaaaayaaaa',
      'aaaaaaaaaayayaaa',
      'aaaaaaaaaaakaaaa',
      'aaaaaaaaaaaaaaaa',
      'aaararaaaaaaaaba',
      'aaabyaaaaaaaabaa',
      'aabraraaaaaaaaaa',
      'aaaakaaabaapapaa',
      'aaaaaaabaaaayaaa',
      'aaaaaaaaaaapapaa',
      'aaaaaaaaaaaakaaa',
      'aaaaaaaaaaaaaaaa',
    ]
  };
  S['tile_fence_h'] = {
    w: 16, h: 16,
    pal: { 'a': '#8cc873:3', 'b': '#5a9648:1', 'w': '#c69a5e:3', 'd': '#8a6236:1', 'k': '#40301c:0' },
    rows: [
      'aaaaaaaaaaaaaaaa',
      'aaaaaaaaaaaaaaaa',
      'aaaaaaaaaaaaaaaa',
      'abaaaaaaaaaaaaaa',
      'aaaaaaaaaaaaaaaa',
      'aakwaaaaaaaakwaa',
      'aakwaaaaaaaakwaa',
      'wwwwwwwwwwwwwwww',
      'dddddddddddddddd',
      'aakwaaaaaaaakwaa',
      'aakwaaaaaaaakwaa',
      'wwwwwwwwwwwwwwww',
      'dddddddddddddddd',
      'aakwaabaaaaakwaa',
      'aakdaaaaaaaakdaa',
      'aaaaaaaaaaaaaaaa',
    ]
  };
  S['tile_fence_v'] = {
    w: 16, h: 16,
    pal: { 'a': '#8cc873:3', 'b': '#5a9648:1', 'w': '#c69a5e:3', 'd': '#8a6236:1', 'k': '#40301c:0' },
    rows: [
      'aaaaaakdwkaaaaaa',
      'aaaaaakdwkaaaaaa',
      'aaaaaakdwkaaaaaa',
      'aabaaakkkkaaaaaa',
      'aaaaaakdwkaaaaaa',
      'aaaaaakdwkaaabaa',
      'aaaaaakdwkaaaaaa',
      'aaaaaakdwkaaaaaa',
      'aaaaaakdwkaaaaaa',
      'aaaaaakdwkaaaaaa',
      'aaaaaakdwkaaaaaa',
      'aaaaaakkkkaaaaaa',
      'aaabaakdwkaaaaaa',
      'aaaaaakdwkaaaaaa',
      'aaaaaakdwkaaaaaa',
      'aaaaaakdwkaaaaaa',
    ]
  };
  S['tile_sign'] = {
    w: 16, h: 16,
    pal: { 'a': '#8cc873:3', 'b': '#5a9648:1', 'w': '#c69a5e:3', 'd': '#8a6236:1', 'k': '#3a2a18:0' },
    rows: [
      'aaaaaaaaaaaaaaaa',
      'aaaaaaaaaaaaaaaa',
      'aaaaaaaaaaaaaaaa',
      'aakkkkkkkkkkkkaa',
      'aakwwwwwwwwwwkaa',
      'aakddddddddddkaa',
      'aakwwwwwwwwwwkaa',
      'aakwwwwwwwwwwkaa',
      'aakkkkkkkkkkkkaa',
      'aaaaaaakdaaaaaaa',
      'aaaaaaakdaaaaaaa',
      'aaaaaaakdaaaaaaa',
      'aaaaaaakdaaaabaa',
      'aabaaaakdaaaaaaa',
      'aaaaaaakdaaaaaaa',
      'aaaaaaaaaaaaaaaa',
    ]
  };
  S['tile_ledge'] = {
    w: 16, h: 16,
    pal: { 'a': '#8cc873:3', 'b': '#5a9648:1', 'e': '#b98a4e:2', 'f': '#8a5f2e:1', 'h': '#e0c07c:3' },
    rows: [
      'aaaaaaaaaaaaaaaa',
      'aaaaaaaaaaaaaaaa',
      'aaaabaaaaaaaaaaa',
      'aaabaaaaaaaaabaa',
      'aaaaaaaabaaabaaa',
      'aaaaaaabaaaaaaaa',
      'aaaaaaaaaaaaaaaa',
      'aaaaaaaaaaaaaaaa',
      'aaaaaaaaaaaaaaaa',
      'aaaaaaaaaaaaaaaa',
      'aaaaaaaaaaaaaaaa',
      'hhhhhhhhhhhhhhhh',
      'feeefeeefeeefeee',
      'eeeeeeeeeeeeeeee',
      'eefeeefeeefeeefe',
      'ffffffffffffffff',
    ]
  };
  S['tile_rock'] = {
    w: 16, h: 16,
    pal: { 'a': '#8cc873:3', 'b': '#5a9648:1', 'm': '#9a9aa2:2', 'd': '#6c6c76:1', 'h': '#c4c4cc:3', 'k': '#33333a:0' },
    rows: [
      'aaaaaaaaaaaaaaaa',
      'aaaaaaaaaaaaaaaa',
      'aabaaaaaaaaaaaaa',
      'aaaaaaaaaaaaabaa',
      'aaaaakkkkkkaaaaa',
      'aaakkmmmdddkkaaa',
      'aakhmmmmmddddkaa',
      'aakhhmmmmmdddkaa',
      'aakhhhmmmmmddkaa',
      'aaakhhmmmmmmdkaa',
      'aaakhhhmmmmmdkaa',
      'aaaakhhhmmmmkaaa',
      'aaaakhhhhmmkaaaa',
      'aabaakkkkkkkaaaa',
      'aaaaaaaaaaaaaaaa',
      'aaaaaaaaaaaaaaaa',
    ]
  };
  S['tile_bush'] = {
    w: 16, h: 16,
    pal: { 'a': '#8cc873:3', 'b': '#5a9648:1', 'd': '#2e6b30:1', 'm': '#4f9e4c:2', 'l': '#83cf74:3', 'k': '#1c3a1c:0' },
    rows: [
      'aaaaaaaaaaaaaaaa',
      'aaaaaaaaaaaaaaaa',
      'aabaaaaaaaaaaaaa',
      'aaaaaakkkkaaaaaa',
      'aaaaaakmdkaaaaaa',
      'aaakkkmmmdkkkaaa',
      'aakmmmmmmddddkaa',
      'aakmmmmmmmdddkaa',
      'aaklmmmmmmmddkaa',
      'aakllmmmmmmddkaa',
      'aakllmmmmmmmdkaa',
      'aaklllmmmmmmmkaa',
      'aaaklllmmmmmkaaa',
      'aaaaklllmmmkabaa',
      'aaaaakkkkkkaaaaa',
      'aaaaaaaaaaaaaaaa',
    ]
  };
  S['tile_lamp'] = {
    w: 16, h: 16,
    pal: { 'a': '#c9c9d2:3', 'b': '#a3a3ae:2', 'k': '#26262c:0', 'y': '#f6e074:3', 'o': '#c8a030:2' },
    rows: [
      'aaaaaaaabaaaaaaa',
      'aaaaaakkkaaaaaaa',
      'aaaaakyoykaaaaaa',
      'aaaaakoyykaaaaaa',
      'aaaaakyyykaaaaaa',
      'aaaaakyyykaaaaaa',
      'aaaaaakkkaaaaaaa',
      'aaaaaakkkaaaaaaa',
      'bbbbbbkkkbbbbbbb',
      'aaaaaaakkaaaaaaa',
      'aaaaaaakkaaaaaaa',
      'aaaaaaakkaaaaaaa',
      'aaaaaaakkaaaaaaa',
      'aaaaaaakkaaaaaaa',
      'aaaaakkkkkkaaaaa',
      'aaaaakkkkkkaaaaa',
    ]
  };
  S['tile_bench'] = {
    w: 16, h: 16,
    pal: { 'a': '#c9c9d2:3', 'b': '#a3a3ae:2', 'w': '#c69a5e:3', 'd': '#8a6236:1', 'k': '#40301c:0' },
    rows: [
      'aaaaaaaaaaaaaaaa',
      'aaaaaaaaaaaaaaaa',
      'aabaaaaaaaaaaaaa',
      'aaaaaaaaaaaaaaaa',
      'aaaaaaaaaaaaaaaa',
      'aaaaaaaaaaaaaaaa',
      'aaaaaaaaaaaaaaaa',
      'aakkkkkkkkkkkkaa',
      'aawwwwwwwwwwwwaa',
      'aaddddddddddddaa',
      'aawwwwwwwwwwwwaa',
      'aaddddddddddddaa',
      'aaakdaaaaaakdaaa',
      'aaakdaaaaaakdbaa',
      'aaakdaaaaaakdaaa',
      'aaaaaaaaaaaaaaaa',
    ]
  };
  S['tile_grass_edge_dirt'] = {
    w: 16, h: 16,
    pal: { 'a': '#8cc873:3', 'b': '#5a9648:1', 'p': '#dcbb7c:2', 'q': '#b2905a:1' },
    rows: [
      'aaaaaaaaaaaaaaaa',
      'aaaaaaaabaaaaaaa',
      'aaaabaabaaaaaaaa',
      'aaabaaaaaaaaaaaa',
      'aaaaaaaaaaaabaaa',
      'aaaaaaaaaaabaaaa',
      'aaaaaaaaaaaaaaaa',
      'aaaaaaaaaaaaaaaa',
      'pppppppppppppppp',
      'pppppppppppppppp',
      'pppqpppppppppppp',
      'ppppppppppppqppp',
      'pppppppppppppppp',
      'pppppppqpppppppp',
      'pppppppppppppppp',
      'pppppppppppppppp',
    ]
  };
  S['tile_flowerbed'] = {
    w: 16, h: 16,
    pal: { 'a': '#8a5a34:1', 'b': '#6f4526:0', 'r': '#e0504a:1', 'y': '#f6d84a:3', 'p': '#f08ab0:3', 'l': '#4e8a3e:2' },
    rows: [
      'aaaaaaaabaaaaaaa',
      'abaaaalaaaaaaaaa',
      'aalaaayaaalaaaba',
      'aaraaaaaaapaaaaa',
      'aaaaaaalaaaaaaaa',
      'aaaaaaapaaaaalaa',
      'aaaaaaaaaaabaraa',
      'aaabaaaalaaaaaaa',
      'aaaalaaapaaaaaaa',
      'aaaayaaaaaaaaaaa',
      'aaaaaaaaabaalaaa',
      'aaalaaaaaaaaraaa',
      'aaayaaaaaaalaaaa',
      'aaaaabaaaaayaaaa',
      'aabaaaaaaaaaabaa',
      'aaaaaaaaaaaaaaaa',
    ]
  };
  S['tile_sand'] = {
    w: 16, h: 16,
    pal: { 'a': '#e9d19a:3', 'b': '#cdae72:2' },
    rows: [
      'aaaaaaaaaaaaaaaa',
      'aaaaaaaaaaaaaaaa',
      'aaaaaaaaaaaaabaa',
      'aaaaaaaaaaaaaaaa',
      'aaabaaaaaaaaaaaa',
      'aaaaaaaaaaaaaaaa',
      'aaaaaaaaaaaaaaaa',
      'aaaaaaaaaaaaaaaa',
      'aaaaaaaaaaabaaaa',
      'aaaaaaaaaaaaaaaa',
      'aaaaaaaaaaaaaaaa',
      'aaaaaaaaaaaaaaaa',
      'aaaaaaabaaaaaaaa',
      'aaaaaaaaaaaaaaaa',
      'aaaaaaaaaaaaaaaa',
      'aaaaaaaaaaaaaaaa',
    ]
  };
  S['tile_water_edge'] = {
    w: 16, h: 16,
    pal: { 'a': '#8cc873:3', 'b': '#5a9648:1', 's': '#e9d19a:3', 'w': '#4f8ad0:2', 'c': '#a8d8fb:3' },
    rows: [
      'aaaaaaaaaaaaaaaa',
      'aaaaaaaaaaaaaaaa',
      'aaabaaaaaaaaaaaa',
      'aaaaaaaaaaaabaaa',
      'aaaaaaaaaaaaaaaa',
      'sasasasasasasasa',
      'ssssssssssssssss',
      'wwwwwwwwwwwwwwww',
      'wwwwwwwwwwwwwwww',
      'wwwcwwwwwwwwwwww',
      'wwwwwwwwwwwwwwww',
      'wwwwwwwwwwcwwwww',
      'wwwwwwwwwwwwwwww',
      'wwwwwwcwwwwwwwww',
      'wwwwwwwwwwwwwwww',
      'wwwwwwwwwwwwwwww',
    ]
  };
  S['tile_roof_l'] = {
    w: 16, h: 16,
    pal: { 'r': '#d85850:2', 'q': '#a03830:1', 'x': '#f0908a:3', 'k': '#5c1c18:0' },
    rows: [
      'kxxxxxxxxxxxxxxx',
      'kxrrrrrrrrrrrrrr',
      'krxrrrrrrrrrrrrr',
      'krrxrrrrrrrrrrrr',
      'krrrxrrrrrrrrrrr',
      'kqqqqxqqqqqqqqqq',
      'krrrrrrrrrrrrrrr',
      'krrrrrrrrrrrrrrr',
      'krrrrrrrrrrrrrrr',
      'krrrrrrrrrrrrrrr',
      'kqqqqqqqqqqqqqqq',
      'krrrrrrrrrrrrrrr',
      'krrrrrrrrrrrrrrr',
      'krrrrrrrrrrrrrrr',
      'krrrrrrrrrrrrrrr',
      'kkkkkkkkkkkkkkkk',
    ]
  };
  S['tile_roof_m'] = {
    w: 16, h: 16,
    pal: { 'r': '#d85850:2', 'q': '#a03830:1', 'x': '#f0908a:3', 'k': '#5c1c18:0' },
    rows: [
      'xxxxxxxxxxxxxxxx',
      'rrrrrrrrrrrrrrrr',
      'rrrrrrrrrrrrrrrr',
      'rrrrrrrrrrrrrrrr',
      'rrrrrrrrrrrrrrrr',
      'qqqqqqqqqqqqqqqq',
      'rrrrrrrrrrrrrrrr',
      'rrrrrrrrrrrrrrrr',
      'rrrrrrrrrrrrrrrr',
      'rrrrrrrrrrrrrrrr',
      'qqqqqqqqqqqqqqqq',
      'rrrrrrrrrrrrrrrr',
      'rrrrrrrrrrrrrrrr',
      'rrrrrrrrrrrrrrrr',
      'rrrrrrrrrrrrrrrr',
      'kkkkkkkkkkkkkkkk',
    ]
  };
  S['tile_roof_r'] = {
    w: 16, h: 16,
    pal: { 'r': '#d85850:2', 'q': '#a03830:1', 'x': '#f0908a:3', 'k': '#5c1c18:0' },
    rows: [
      'xxxxxxxxxxxxxxxk',
      'rrrrrrrrrrrrrrxk',
      'rrrrrrrrrrrrrxrk',
      'rrrrrrrrrrrrxrrk',
      'rrrrrrrrrrrxrrrk',
      'qqqqqqqqqqxqqqqk',
      'rrrrrrrrrrrrrrrk',
      'rrrrrrrrrrrrrrrk',
      'rrrrrrrrrrrrrrrk',
      'rrrrrrrrrrrrrrrk',
      'qqqqqqqqqqqqqqqk',
      'rrrrrrrrrrrrrrrk',
      'rrrrrrrrrrrrrrrk',
      'rrrrrrrrrrrrrrrk',
      'rrrrrrrrrrrrrrrk',
      'kkkkkkkkkkkkkkkk',
    ]
  };
  S['tile_roof2_l'] = {
    w: 16, h: 16,
    pal: { 'r': '#d85850:2', 'q': '#a03830:1', 'k': '#5c1c18:0' },
    rows: [
      'krrrrrrrrrrrrrrr',
      'krrrrrrrrrrrrrrr',
      'krrrrrrrrrrrrrrr',
      'krrrrrrrrrrrrrrr',
      'kqqqqqqqqqqqqqqq',
      'krrrrrrrrrrrrrrr',
      'krrrrrrrrrrrrrrr',
      'krrrrrrrrrrrrrrr',
      'krrrrrrrrrrrrrrr',
      'kqqqqqqqqqqqqqqq',
      'krrrrrrrrrrrrrrr',
      'krrrrrrrrrrrrrrr',
      'krrrrrrrrrrrrrrr',
      'kqqqqqqqqqqqqqqq',
      'kqqqqqqqqqqqqqqq',
      'kkkkkkkkkkkkkkkk',
    ]
  };
  S['tile_roof2_m'] = {
    w: 16, h: 16,
    pal: { 'r': '#d85850:2', 'q': '#a03830:1', 'k': '#5c1c18:0' },
    rows: [
      'rrrrrrrrrrrrrrrr',
      'rrrrrrrrrrrrrrrr',
      'rrrrrrrrrrrrrrrr',
      'rrrrrrrrrrrrrrrr',
      'qqqqqqqqqqqqqqqq',
      'rrrrrrrrrrrrrrrr',
      'rrrrrrrrrrrrrrrr',
      'rrrrrrrrrrrrrrrr',
      'rrrrrrrrrrrrrrrr',
      'qqqqqqqqqqqqqqqq',
      'rrrrrrrrrrrrrrrr',
      'rrrrrrrrrrrrrrrr',
      'rrrrrrrrrrrrrrrr',
      'qqqqqqqqqqqqqqqq',
      'qqqqqqqqqqqqqqqq',
      'kkkkkkkkkkkkkkkk',
    ]
  };
  S['tile_roof2_r'] = {
    w: 16, h: 16,
    pal: { 'r': '#d85850:2', 'q': '#a03830:1', 'k': '#5c1c18:0' },
    rows: [
      'rrrrrrrrrrrrrrrk',
      'rrrrrrrrrrrrrrrk',
      'rrrrrrrrrrrrrrrk',
      'rrrrrrrrrrrrrrrk',
      'qqqqqqqqqqqqqqqk',
      'rrrrrrrrrrrrrrrk',
      'rrrrrrrrrrrrrrrk',
      'rrrrrrrrrrrrrrrk',
      'rrrrrrrrrrrrrrrk',
      'qqqqqqqqqqqqqqqk',
      'rrrrrrrrrrrrrrrk',
      'rrrrrrrrrrrrrrrk',
      'rrrrrrrrrrrrrrrk',
      'qqqqqqqqqqqqqqqk',
      'qqqqqqqqqqqqqqqk',
      'kkkkkkkkkkkkkkkk',
    ]
  };
  S['tile_wall'] = {
    w: 16, h: 16,
    pal: { 'w': '#f0e0bc:3', 'v': '#d0b888:2', 'k': '#3a2a18:0' },
    rows: [
      'wwvwwwvwwwvwwwvw',
      'wwvwwwvwwwvwwwvw',
      'wwvwwwvwwwvwwwvw',
      'wwvwwwvwwwvwwwvw',
      'wwvwwwvwwwvwwwvw',
      'wwvwwwvwwwvwwwvw',
      'wwvwwwvwwwvwwwvw',
      'wwvwwwvwwwvwwwvw',
      'wwvwwwvwwwvwwwvw',
      'wwvwwwvwwwvwwwvw',
      'wwvwwwvwwwvwwwvw',
      'wwvwwwvwwwvwwwvw',
      'wwvwwwvwwwvwwwvw',
      'wwvwwwvwwwvwwwvw',
      'wwvwwwvwwwvwwwvw',
      'vvvvvvvvvvvvvvvv',
    ]
  };
  S['tile_wall_l'] = {
    w: 16, h: 16,
    pal: { 'w': '#f0e0bc:3', 'v': '#d0b888:2', 'k': '#3a2a18:0' },
    rows: [
      'kwvwwwvwwwvwwwvw',
      'kwvwwwvwwwvwwwvw',
      'kwvwwwvwwwvwwwvw',
      'kwvwwwvwwwvwwwvw',
      'kwvwwwvwwwvwwwvw',
      'kwvwwwvwwwvwwwvw',
      'kwvwwwvwwwvwwwvw',
      'kwvwwwvwwwvwwwvw',
      'kwvwwwvwwwvwwwvw',
      'kwvwwwvwwwvwwwvw',
      'kwvwwwvwwwvwwwvw',
      'kwvwwwvwwwvwwwvw',
      'kwvwwwvwwwvwwwvw',
      'kwvwwwvwwwvwwwvw',
      'kwvwwwvwwwvwwwvw',
      'kvvvvvvvvvvvvvvv',
    ]
  };
  S['tile_wall_r'] = {
    w: 16, h: 16,
    pal: { 'w': '#f0e0bc:3', 'v': '#d0b888:2', 'k': '#3a2a18:0' },
    rows: [
      'wwvwwwvwwwvwwwvk',
      'wwvwwwvwwwvwwwvk',
      'wwvwwwvwwwvwwwvk',
      'wwvwwwvwwwvwwwvk',
      'wwvwwwvwwwvwwwvk',
      'wwvwwwvwwwvwwwvk',
      'wwvwwwvwwwvwwwvk',
      'wwvwwwvwwwvwwwvk',
      'wwvwwwvwwwvwwwvk',
      'wwvwwwvwwwvwwwvk',
      'wwvwwwvwwwvwwwvk',
      'wwvwwwvwwwvwwwvk',
      'wwvwwwvwwwvwwwvk',
      'wwvwwwvwwwvwwwvk',
      'wwvwwwvwwwvwwwvk',
      'vvvvvvvvvvvvvvvk',
    ]
  };
  S['tile_window'] = {
    w: 16, h: 16,
    pal: { 'w': '#f0e0bc:3', 'v': '#d0b888:2', 'k': '#3a2a18:0', 'g': '#bce4f6:3' },
    rows: [
      'wwvwwwvwwwvwwwvw',
      'wwvwwwvwwwvwwwvw',
      'wwvwwwvwwwvwwwvw',
      'wwvwkkkkkkkkwwvw',
      'wwvwkgggkggkwwvw',
      'wwvwkgggkggkwwvw',
      'wwvwkgggkggkwwvw',
      'wwvwkkkkkkkkwwvw',
      'wwvwkgggkggkwwvw',
      'wwvwkgggkggkwwvw',
      'wwvwkkkkkkkkwwvw',
      'wwvwwwvwwwvwwwvw',
      'wwvwwwvwwwvwwwvw',
      'wwvwwwvwwwvwwwvw',
      'wwvwwwvwwwvwwwvw',
      'vvvvvvvvvvvvvvvv',
    ]
  };
  S['tile_door'] = {
    w: 16, h: 16,
    pal: { 'w': '#f0e0bc:3', 'v': '#d0b888:2', 'k': '#3a2a18:0', 'd': '#8a5a2e:1', 'n': '#f0e0bc:3' },
    rows: [
      'wwwwwwwwwwwwwwww',
      'wwwwwwwwwwwwwwww',
      'vvvvvvvvvvvvvvvv',
      'wwkkkkkkkkkkkkww',
      'wwkdddddkddddkww',
      'wwkvvvvvkvvvvvww',
      'wwkdddddkddddkww',
      'wwkdddddkddddkww',
      'wwkvvvvvkvvvvvww',
      'wwkdddddkdnndkww',
      'wwkdddddkddddkww',
      'wwkvvvvvkvvvvvww',
      'wwkdddddkddddkww',
      'wwkdddddkddddkww',
      'wwkvvvvvkvvvvvww',
      'wwkkkkkkkkkkkkww',
    ]
  };
  S['tile_sign_mart'] = {
    w: 16, h: 16,
    pal: { 'w': '#f0e0bc:3', 'v': '#d0b888:2', 'k': '#3a2a18:0', 'b': '#3868c8:2', 'c': '#203c8a:1', 't': '#f0e0bc:3' },
    rows: [
      'wwvwwwvwwwvwwwvw',
      'wwvwwwvwwwvwwwvw',
      'wwvwwwvwwwvwwwvw',
      'cccccccccccccccc',
      'bbbbbbbbbbbbbbbb',
      'bbbbbbbbbbbbbbbb',
      'tbtbbtbbttbbtttb',
      'tttbtbtbtbtbbtbb',
      'tttbtttbttbbbtbb',
      'tbtbtbtbtbtbbtbb',
      'tbtbtbtbtbtbbtbb',
      'cccccccccccccccc',
      'wwvwwwvwwwvwwwvw',
      'wwvwwwvwwwvwwwvw',
      'wwvwwwvwwwvwwwvw',
      'vvvvvvvvvvvvvvvv',
    ]
  };
  S['tile_sign_center'] = {
    w: 16, h: 16,
    pal: { 'w': '#f0e0bc:3', 'v': '#d0b888:2', 'k': '#3a2a18:0', 'b': '#f8f4e8:3', 'c': '#c8bfa0:2', 'h': '#e05868:1', 'j': '#f08898:3' },
    rows: [
      'wwvwwwvwwwvwwwvw',
      'wwvwwwvwwwvwwwvw',
      'wwvwwwvwwwvwwwvw',
      'wwccccccccccccvw',
      'wwcbbbbbbbbbbcvw',
      'wwcbbjhbbjhbbcvw',
      'wwcbhhhhhhhhbcvw',
      'wwcbhhhhhhhhbcvw',
      'wwcbbhhhhhhbbcvw',
      'wwcbbbhhhhbbbcvw',
      'wwcbbbbhhbbbbcvw',
      'wwccccccccccccvw',
      'wwvwwwvwwwvwwwvw',
      'wwvwwwvwwwvwwwvw',
      'wwvwwwvwwwvwwwvw',
      'vvvvvvvvvvvvvvvv',
    ]
  };
  S['tile_sign_lab'] = {
    w: 16, h: 16,
    pal: { 'w': '#f0e0bc:3', 'v': '#d0b888:2', 'k': '#3a2a18:0', 'b': '#f8f4e8:3', 'c': '#c8bfa0:2', 'f': '#68c8b0:2', 'l': '#307860:1', 's': '#e8a840:3' },
    rows: [
      'wwvwwwvwwwvwwwvw',
      'wwvwwwvwwwvwwwvw',
      'wwvwwwvwwwvwwwvw',
      'wwccccccccccccvw',
      'wwcbbbbbbbbbbcvw',
      'wwcbbbbllbbbbcvw',
      'wwcbbbbllbbbbcvw',
      'wwcbbbllllbbbcvw',
      'wwcbbllllllbbcvw',
      'wwcbblfffflbbcvw',
      'wwcbblfsfflbbcvw',
      'wwccclfffflcccvw',
      'wwvwwwllllvwwwvw',
      'wwvwwwvwwwvwwwvw',
      'wwvwwwvwwwvwwwvw',
      'vvvvvvvvvvvvvvvv',
    ]
  };
  S['tile_sign_gym'] = {
    w: 16, h: 16,
    pal: { 'w': '#f0e0bc:3', 'v': '#d0b888:2', 'k': '#3a2a18:0', 'b': '#f8f4e8:3', 'c': '#c8bfa0:2', 's': '#e8c840:1', 'o': '#a87c18:0' },
    rows: [
      'wwvwwwvwwwvwwwvw',
      'wwvwwwvwwwvwwwvw',
      'wwvwwwvwwwvwwwvw',
      'wwccccccccccccvw',
      'wwcbbbbbsbbbbcvw',
      'wwcbbbbsosbbbcvw',
      'wwcbbbssossbbcvw',
      'wwcbbbbsssbbbcvw',
      'wwcbbbsbbbsbbcvw',
      'wwcbbbbbbbbbbcvw',
      'wwcbbbbbbbbbbcvw',
      'wwccccccccccccvw',
      'wwvwwwvwwwvwwwvw',
      'wwvwwwvwwwvwwwvw',
      'wwvwwwvwwwvwwwvw',
      'vvvvvvvvvvvvvvvv',
    ]
  };
  S['tile_sign_vh'] = {
    w: 16, h: 16,
    pal: { 'w': '#f0e0bc:3', 'v': '#d0b888:2', 'k': '#3a2a18:0', 'b': '#fbfbf6:3', 'c': '#c8bfa0:2', 'l': '#3ba050:2' },
    rows: [
      'wwvwwwvwwwvwwwvw',
      'wwvwwwvwwwvwwwvw',
      'wwvwwwvwwwvwwwvw',
      'wwccccccccccccvw',
      'wwcbbbbbbbbbbcvw',
      'wwcblblbblblbcvw',
      'wwcblblbblblbcvw',
      'wwcblblbblllbcvw',
      'wwcblblbblblbcvw',
      'wwcbblbbblblbcvw',
      'wwcbbbbbbbbbbcvw',
      'wwccccccccccccvw',
      'wwvwwwvwwwvwwwvw',
      'wwvwwwvwwwvwwwvw',
      'wwvwwwvwwwvwwwvw',
      'vvvvvvvvvvvvvvvv',
    ]
  };
  S['tile_sign_violet'] = {
    w: 16, h: 16,
    pal: { 'w': '#f0e0bc:3', 'v': '#d0b888:2', 'k': '#3a2a18:0', 'b': '#fbfbf6:3', 'c': '#c8bfa0:2', 'p': '#8850c0:1' },
    rows: [
      'wwvwwwvwwwvwwwvw',
      'wwvwwwvwwwvwwwvw',
      'wwvwwwvwwwvwwwvw',
      'wwccccccccccccvw',
      'wwcppbbbbbbppcvw',
      'wwcbppbbbbppbcvw',
      'wwcbbppbbbppbcvw',
      'wwcbbppbbppbbcvw',
      'wwcbbbppppbbbcvw',
      'wwcbbbbppbbbbcvw',
      'wwcbbbbpppbbbcvw',
      'wwccccccccccccvw',
      'wwvwwwvwwwvwwwvw',
      'wwvwwwvwwwvwwwvw',
      'wwvwwwvwwwvwwwvw',
      'vvvvvvvvvvvvvvvv',
    ]
  };
})();
