// AUTO-STYLE-GENERATED pixel data — hand-designed, programmatically emitted for accuracy.
(function () {
  const S = window.SPRITES = window.SPRITES || {};
  S['tile_floor'] = {
    w: 16, h: 16,
    pal: { a: '#e4b074:3', b: '#c8945c:3', c: '#7c4e28:3', d: '#f8d8a8:3' },
    rows: [
      'aaadaaaaaaadaaaa',
      'aaaaaadaaaaaadaa',
      'aaaaaaaaaaaaaaaa',
      'cccccccccccccccc',
      'bbbdbbbbbbbdbbbb',
      'bbbbbbdbbbbbbdbb',
      'bbbbbbbbbbbbbbbb',
      'cccccccccccccccc',
      'aaadaaaaaaadaaaa',
      'aaaaaadaaaaaadaa',
      'aaaaaaaaaaaaaaaa',
      'cccccccccccccccc',
      'bbbdbbbbbbbdbbbb',
      'bbbbbbdbbbbbbdbb',
      'bbbbbbbbbbbbbbbb',
      'cccccccccccccccc',
    ]
  };
  S['tile_floor_tile'] = {
    w: 16, h: 16,
    pal: { 'a': '#f2ecda:3', 'b': '#cfc2a0:2' },
    rows: [
      'aaaaaaaabbbbbbbb',
      'aaaaaaaabbbbbbbb',
      'aaaaaaaabbbbbbbb',
      'aaaaaaaabbbbbbbb',
      'aaaaaaaabbbbbbbb',
      'aaaaaaaabbbbbbbb',
      'aaaaaaaabbbbbbbb',
      'aaaaaaaabbbbbbbb',
      'bbbbbbbbaaaaaaaa',
      'bbbbbbbbaaaaaaaa',
      'bbbbbbbbaaaaaaaa',
      'bbbbbbbbaaaaaaaa',
      'bbbbbbbbaaaaaaaa',
      'bbbbbbbbaaaaaaaa',
      'bbbbbbbbaaaaaaaa',
      'bbbbbbbbaaaaaaaa',
    ]
  };
  S['tile_rug'] = {
    w: 16, h: 16,
    pal: { 'a': '#e8683c:2', 'b': '#f6c667:3', 'c': '#8a2c18:0', 'd': '#b8341c:1' },
    rows: [
      'cccccccccccccccc',
      'cbbbbbbbbbbbbbbc',
      'cbaaaaaaaaaaaabc',
      'cbaaaaaaaaaaaabc',
      'cbaaaaaaaaaaaabc',
      'cbaaaaaddaaaaabc',
      'cbaaaaddddaaaabc',
      'cbaaaddddddaaabc',
      'cbaaaddddddaaabc',
      'cbaaaaddddaaaabc',
      'cbaaaaaddaaaaabc',
      'cbaaaaaaaaaaaabc',
      'cbaaaaaaaaaaaabc',
      'cbaaaaaaaaaaaabc',
      'cbbbbbbbbbbbbbbc',
      'cccccccccccccccc',
    ]
  };
  S['tile_carpet_purple'] = {
    w: 16, h: 16,
    pal: { 'a': '#7c3fa8:1', 'b': '#6a2f96:1', 'c': '#4a1f6e:0', 'd': '#a868d0:2' },
    rows: [
      'aaadaaaaaaadaaaa',
      'aaaaaadaaaaaadaa',
      'aaaaaaaaaaaaaaaa',
      'cccccccccccccccc',
      'bbbdbbbbbbbdbbbb',
      'bbbbbbdbbbbbbdbb',
      'bbbbbbbbbbbbbbbb',
      'cccccccccccccccc',
      'aaadaaaaaaadaaaa',
      'aaaaaadaaaaaadaa',
      'aaaaaaaaaaaaaaaa',
      'cccccccccccccccc',
      'bbbdbbbbbbbdbbbb',
      'bbbbbbdbbbbbbdbb',
      'bbbbbbbbbbbbbbbb',
      'cccccccccccccccc',
    ]
  };
  S['tile_mat'] = {
    w: 16, h: 16,
    pal: { 'a': '#e4b074:2', 'b': '#c8945c:1', 'c': '#7c4e28:0', 'd': '#f8d8a8:3', 'm': '#c8a068:2', 'n': '#a07840:1', 'o': '#6c4828:0' },
    rows: [
      'aaadaaaaaaadaaaa',
      'aaaaaadaaaaaadaa',
      'aaaaaaaaaaaaaaaa',
      'ccoooooooooooocc',
      'bbommmmmmmmmmobb',
      'bbonnnnnnnnnnobb',
      'bbommmmmmmmmmobb',
      'cconnnnnnnnnnocc',
      'aaommmmmmmmmmoaa',
      'aaonnnnnnnnnnoaa',
      'aaommmmmmmmmmoaa',
      'cconnnnnnnnnnocc',
      'bboooooooooooobb',
      'bbbbbbdbbbbbbdbb',
      'bbbbbbbbbbbbbbbb',
      'cccccccccccccccc',
    ]
  };
  S['tile_wall_in'] = {
    w: 16, h: 16,
    pal: { 'a': '#f0e8d0:3', 'b': '#d0a860:2', 'c': '#e6d8ba:3', 'd': '#c8b088:2', 'e': '#6c4828:1' },
    rows: [
      'bbbbbbbbbbbbbbbb',
      'bbbbbbbbbbbbbbbb',
      'aaaacaaaaaacaaaa',
      'aaaacaaaaaacaaaa',
      'aaaacaaaaaacaaaa',
      'aaaacaaaaaacaaaa',
      'aaaacaaaaaacaaaa',
      'aaaacaaaaaacaaaa',
      'aaaacaaaaaacaaaa',
      'aaaacaaaaaacaaaa',
      'aaaacaaaaaacaaaa',
      'aaaacaaaaaacaaaa',
      'aaaacaaaaaacaaaa',
      'dddddddddddddddd',
      'eeeeeeeeeeeeeeee',
      'eeeeeeeeeeeeeeee',
    ]
  };
  S['tile_window_in'] = {
    w: 16, h: 16,
    pal: { 'a': '#f0e8d0:3', 'b': '#d0a860:2', 'c': '#e6d8ba:3', 'd': '#c8b088:2', 'e': '#6c4828:1', 'f': '#8a5a30:1', 's': '#a8d8f5:3', 't': '#6fb0dc:2', 'w': '#ffffff:3' },
    rows: [
      'bbbbbbbbbbbbbbbb',
      'bbbbbbbbbbbbbbbb',
      'aaaacaaaaaacaaaa',
      'aaaffffffffffaaa',
      'aaafswwsfsssfaaa',
      'aaafswssfsssfaaa',
      'aaaffffffffffaaa',
      'aaafttttftttfaaa',
      'aaafttttftttfaaa',
      'aaafttttftttfaaa',
      'aaaffffffffffaaa',
      'aaaacaaaaaacaaaa',
      'aaaacaaaaaacaaaa',
      'dddddddddddddddd',
      'eeeeeeeeeeeeeeee',
      'eeeeeeeeeeeeeeee',
    ]
  };
  S['tile_poster_vh'] = {
    w: 16, h: 16,
    pal: { 'a': '#f0e8d0:3', 'b': '#d0a860:2', 'c': '#e6d8ba:3', 'd': '#c8b088:2', 'e': '#6c4828:1', 'p': '#2f9152:1', 'w': '#f8f8f4:3' },
    rows: [
      'bbbbbbbbbbbbbbbb',
      'bbbbbbbbbbbbbbbb',
      'aaaacaaaaaacaaaa',
      'aaappppppppppaaa',
      'aaapwwwwwwwwpaaa',
      'aaapwpwpwpwppaaa',
      'aaapwpwpwpwppaaa',
      'aaapwpwpwppppaaa',
      'aaapwwpwwpwppaaa',
      'aaapwwwwwwwwpaaa',
      'aaapwwwwwwwwpaaa',
      'aaappppppppppaaa',
      'aaaacaaaaaacaaaa',
      'dddddddddddddddd',
      'eeeeeeeeeeeeeeee',
      'eeeeeeeeeeeeeeee',
    ]
  };
  S['tile_poster_violet'] = {
    w: 16, h: 16,
    pal: { 'a': '#f0e8d0:3', 'b': '#d0a860:2', 'c': '#e6d8ba:3', 'd': '#c8b088:2', 'e': '#6c4828:1', 'p': '#7c3fa8:1', 'q': '#5a2c80:0', 'w': '#f8f8f4:3' },
    rows: [
      'bbbbbbbbbbbbbbbb',
      'bbbbbbbbbbbbbbbb',
      'aaaacaaaaaacaaaa',
      'aaaqqqqqqqqqqaaa',
      'aaaqppppppppqaaa',
      'aaaqpwppppwpqaaa',
      'aaaqpwwppwwpqaaa',
      'aaaqppwppwppqaaa',
      'aaaqpppwwpppqaaa',
      'aaaqppppppppqaaa',
      'aaaqppppppppqaaa',
      'aaaqqqqqqqqqqaaa',
      'aaaacaaaaaacaaaa',
      'dddddddddddddddd',
      'eeeeeeeeeeeeeeee',
      'eeeeeeeeeeeeeeee',
    ]
  };
  S['tile_banner_m'] = {
    w: 16, h: 16,
    pal: { 'a': '#f0e8d0:3', 'b': '#3878c8:1', 'c': '#e6d8ba:3', 'd': '#c8b088:2', 'e': '#6c4828:1', 's': '#3a2a18:0', 'r': '#d8402c:1', 'y': '#f0c030:2', 'n': '#48a860:1' },
    rows: [
      'bbbbbbbbbbbbbbbb',
      'bbbbbbbbbbbbbbbb',
      'ssssssssssssssss',
      'rrrryyyybbbbnnnn',
      'rrrryyyybbbbnnnn',
      'arraayyaabbaanna',
      'arraayyaabbaanna',
      'arraayyaabbaanna',
      'aaaacaaaaaacaaaa',
      'aaaacaaaaaacaaaa',
      'aaaacaaaaaacaaaa',
      'aaaacaaaaaacaaaa',
      'aaaacaaaaaacaaaa',
      'dddddddddddddddd',
      'eeeeeeeeeeeeeeee',
      'eeeeeeeeeeeeeeee',
    ]
  };
  S['tile_banner_l'] = {
    w: 16, h: 16,
    pal: { 'a': '#f0e8d0:3', 'b': '#3878c8:1', 'c': '#e6d8ba:3', 'd': '#c8b088:2', 'e': '#6c4828:1', 's': '#3a2a18:0', 'k': '#241a10:0', 'y': '#f0c030:2', 'n': '#48a860:1' },
    rows: [
      'bbbbbbbbbbbbbbbb',
      'bkkbbbbbbbbbbbbb',
      'skksssssssssssss',
      'aaaayyyybbbbnnnn',
      'aaaayyyybbbbnnnn',
      'aaaaayyaabbaanna',
      'aaaaayyaabbaanna',
      'aaaaayyaabbaanna',
      'aaaacaaaaaacaaaa',
      'aaaacaaaaaacaaaa',
      'aaaacaaaaaacaaaa',
      'aaaacaaaaaacaaaa',
      'aaaacaaaaaacaaaa',
      'dddddddddddddddd',
      'eeeeeeeeeeeeeeee',
      'eeeeeeeeeeeeeeee',
    ]
  };
  S['tile_banner_r'] = {
    w: 16, h: 16,
    pal: { 'a': '#f0e8d0:3', 'b': '#3878c8:1', 'c': '#e6d8ba:3', 'd': '#c8b088:2', 'e': '#6c4828:1', 's': '#3a2a18:0', 'k': '#241a10:0', 'r': '#d8402c:1', 'y': '#f0c030:2' },
    rows: [
      'bbbbbbbbbbbbbbbb',
      'bbbbbbbbbbbbbkkb',
      'ssssssssssssskks',
      'rrrryyyybbbbaaaa',
      'rrrryyyybbbbaaaa',
      'arraayyaabbaaaaa',
      'arraayyaabbaaaaa',
      'arraayyaabbaaaaa',
      'aaaacaaaaaacaaaa',
      'aaaacaaaaaacaaaa',
      'aaaacaaaaaacaaaa',
      'aaaacaaaaaacaaaa',
      'aaaacaaaaaacaaaa',
      'dddddddddddddddd',
      'eeeeeeeeeeeeeeee',
      'eeeeeeeeeeeeeeee',
    ]
  };
  S['tile_void'] = {
    w: 16, h: 16,
    pal: { 'k': '#000000:0' },
    rows: [
      'kkkkkkkkkkkkkkkk',
      'kkkkkkkkkkkkkkkk',
      'kkkkkkkkkkkkkkkk',
      'kkkkkkkkkkkkkkkk',
      'kkkkkkkkkkkkkkkk',
      'kkkkkkkkkkkkkkkk',
      'kkkkkkkkkkkkkkkk',
      'kkkkkkkkkkkkkkkk',
      'kkkkkkkkkkkkkkkk',
      'kkkkkkkkkkkkkkkk',
      'kkkkkkkkkkkkkkkk',
      'kkkkkkkkkkkkkkkk',
      'kkkkkkkkkkkkkkkk',
      'kkkkkkkkkkkkkkkk',
      'kkkkkkkkkkkkkkkk',
      'kkkkkkkkkkkkkkkk',
    ]
  };
  S['tile_bed_top'] = {
    w: 16, h: 16,
    pal: { 'k': '#241a10:0', 'h': '#a06838:1', 'p': '#f8f0e0:3', 's': '#d8c8a8:2', 'b': '#d8402c:1', 'c': '#a82818:0' },
    rows: [
      'hhhhhhhhhhhhhhhh',
      'hhhhhhhhhhhhhhhh',
      'kkkkkkkkkkkkkkkk',
      'bbbbbbbbbbbbbbbb',
      'bbkkkkkkkkkkkkbb',
      'bbkppppppppppkbb',
      'bbkppppppppppkbb',
      'bbkppppppppppkbb',
      'bbksssssssssskbb',
      'bbkkkkkkkkkkkkbb',
      'kkkkkkkkkkkkkkkk',
      'bcbbcbbcbbcbbcbb',
      'bcbbcbbcbbcbbcbb',
      'bcbbcbbcbbcbbcbb',
      'bcbbcbbcbbcbbcbb',
      'bbbbbbbbbbbbbbbb',
    ]
  };
  S['tile_bed_bot'] = {
    w: 16, h: 16,
    pal: { 'k': '#241a10:0', 'b': '#d8402c:1', 'c': '#a82818:0', 'f': '#f07050:2', 'w': '#c8945c:2', 'v': '#7c4e28:0' },
    rows: [
      'bcbbcbbcbbcbbcbb',
      'bcbbcbbcbbcbbcbb',
      'bcbbcbbcbbcbbcbb',
      'bcbbcbbcbbcbbcbb',
      'ffffffffffffffff',
      'bcbbcbbcbbcbbcbb',
      'bcbbcbbcbbcbbcbb',
      'bcbbcbbcbbcbbcbb',
      'bcbbcbbcbbcbbcbb',
      'bcbbcbbcbbcbbcbb',
      'bcbbcbbcbbcbbcbb',
      'bcbbcbbcbbcbbcbb',
      'kkkkkkkkkkkkkkkk',
      'wwvwwwwwwwwwwvww',
      'wwvwwwwwwwwwwvww',
      'wwvwwwwwwwwwwvww',
    ]
  };
  S['tile_pc'] = {
    w: 16, h: 16,
    pal: { 'k': '#241a10:0', 'w': '#c8945c:2', 'd': '#8c5c30:1', 'm': '#484850:1', 'n': '#2c2c34:0', 's': '#14283c:0', 'l': '#4090c8:2', 'b': '#b0b0b8:2', 'f': '#e4b074:2' },
    rows: [
      'ffffffffffffffff',
      'fffkkkkkkkkkkfff',
      'fffksssssssskfff',
      'fffkslllsssskfff',
      'fffkslllsssskfff',
      'fffksssssssskfff',
      'fffksssssssskfff',
      'fffksssssssskfff',
      'fffkkkkkkkkkkfff',
      'kkkknkmmmmkkkkkk',
      'wwbbbbbbbbbbbbww',
      'wwbbbbbbbbbbbbww',
      'wddwwwwwwwwwwddw',
      'wddwwwwwwwwwwddw',
      'wddwwwwwwwwwwddw',
      'wddwwwwwwwwwwddw',
    ]
  };
  S['tile_tv'] = {
    w: 16, h: 16,
    pal: { 'k': '#241a10:0', 'm': '#484850:1', 'n': '#2c2c34:0', 's': '#14283c:0', 'l': '#6098c8:2', 'd': '#8c5c30:1', 'a': '#202028:0', 'f': '#e4b074:2' },
    rows: [
      'ffaffffffffffaff',
      'ffkkkkkkkkkkkkff',
      'ffkmmmmmmmmmmkff',
      'ffkmssssssssmkff',
      'ffkmslllllssmkff',
      'ffkmslllllssmkff',
      'ffkmslllllssmkff',
      'ffkmssssssssmkff',
      'ffkmmmmmmmmmmkff',
      'ffkkkkkkkkkkkkff',
      'ffffkkkkkkkkffff',
      'ffffkddddddkffff',
      'ffffkddddddkffff',
      'ffffkddddddkffff',
      'ffnnkddddddknnff',
      'ffffffffffffffff',
    ]
  };
  S['tile_table'] = {
    w: 16, h: 16,
    pal: { 'a': '#d8a868:2', 'b': '#c8945c:1', 'c': '#7c4e28:0' },
    rows: [
      'aabaaaabaaaabaaa',
      'aabaaaabaaaabaaa',
      'aabaaaabaaaabaaa',
      'aabaaaabaaaabaaa',
      'aabaaaabaaaabaaa',
      'aabaaaabaaaabaaa',
      'aabaaaabaaaabaaa',
      'aabaaaabaaaabaaa',
      'aabaaaabaaaabaaa',
      'aabaaaabaaaabaaa',
      'aabaaaabaaaabaaa',
      'aabaaaabaaaabaaa',
      'cccccccccccccccc',
      'bbcbbbbbbbbbbcbb',
      'bbcbbbbbbbbbbcbb',
      'bbcbbbbbbbbbbcbb',
    ]
  };
  S['tile_chair_l'] = {
    w: 16, h: 16,
    pal: { 'k': '#241a10:0', 'a': '#c8945c:2', 'b': '#8c5c30:1', 'f': '#e4b074:2' },
    rows: [
      'ffffffffffffffff',
      'ffkkkfffffffffff',
      'ffkakfffffffffff',
      'ffkakfffffffffff',
      'ffkakfffffffffff',
      'ffkakfffffffffff',
      'ffkakfffffffffff',
      'ffkakfffffffffff',
      'ffkakfffffffffff',
      'ffkkkkkkkkkkkkff',
      'ffkaaaaaaaaaakff',
      'ffkkkkkkkkkkkkff',
      'fffbffffffffbfff',
      'fffbffffffffbfff',
      'fffbffffffffbfff',
      'ffffffffffffffff',
    ]
  };
  S['tile_chair_r'] = {
    w: 16, h: 16,
    pal: { 'k': '#241a10:0', 'a': '#c8945c:2', 'b': '#8c5c30:1', 'f': '#e4b074:2' },
    rows: [
      'ffffffffffffffff',
      'fffffffffffkkkff',
      'fffffffffffkakff',
      'fffffffffffkakff',
      'fffffffffffkakff',
      'fffffffffffkakff',
      'fffffffffffkakff',
      'fffffffffffkakff',
      'fffffffffffkakff',
      'ffkkkkkkkkkkkkff',
      'ffkaaaaaaaaaakff',
      'ffkkkkkkkkkkkkff',
      'fffbffffffffbfff',
      'fffbffffffffbfff',
      'fffbffffffffbfff',
      'ffffffffffffffff',
    ]
  };
  S['tile_shelf'] = {
    w: 16, h: 16,
    pal: { 'k': '#241a10:0', 'm': '#8c5c30:1', 'd': '#603c1c:0', 'r': '#d8402c:2', 'b': '#3878c8:2', 'n': '#48a860:2', 'y': '#f0c030:2', 'p': '#9048c0:2', 't': '#30a8a0:2', 'o': '#e8843c:2' },
    rows: [
      'kkkkkkkkkkkkkkkk',
      'kkmmkmmkmmkmmkmk',
      'krkkykkokkykktkk',
      'krbnyptorbynptok',
      'krbnyptorbynptok',
      'krbnyptorbynptok',
      'krbnyptorbynptok',
      'krknkpkokbknktkk',
      'kddddddddddddddk',
      'kkmkmkmkmkmkmkmk',
      'kbkrknktkrkokpkk',
      'kbyrpnotyrbonptk',
      'kbyrpnotyrbonptk',
      'kbyrpnotyrbonptk',
      'kbyrpnotyrbonptk',
      'kkkkkkkkkkkkkkkk',
    ]
  };
  S['tile_counter'] = {
    w: 16, h: 16,
    pal: { 'k': '#241a10:0', 'a': '#e8c088:3', 'b': '#a86838:1', 'c': '#7c4e28:0', 'e': '#f0c088:3' },
    rows: [
      'kkkkkkkkkkkkkkkk',
      'eeeeeeeeeeeeeeee',
      'aaaaaaaaaaaaaaaa',
      'cccccccccccccccc',
      'cbbbcbbbcbbbcbbb',
      'cbbbcbbbcbbbcbbb',
      'cbbbcbbbcbbbcbbb',
      'cbbbcbbbcbbbcbbb',
      'cbbbcbbbcbbbcbbb',
      'cbbbcbbbcbbbcbbb',
      'cbbbcbbbcbbbcbbb',
      'cbbbcbbbcbbbcbbb',
      'cbbbcbbbcbbbcbbb',
      'cbbbcbbbcbbbcbbb',
      'cbbbcbbbcbbbcbbb',
      'cbbbcbbbcbbbcbbb',
    ]
  };
  S['tile_stairs_up'] = {
    w: 16, h: 16,
    pal: { 'a': '#e8d0a0:3', 'b': '#c8a868:2', 'c': '#8c6838:1' },
    rows: [
      'bbbbbbbbbbbbaaac',
      'bbbbbbbbbbbbaaac',
      'bbbbbbbbbbbbaaac',
      'bbbbbbbbbbbbcccc',
      'bbbbbbbbaaacbbbb',
      'bbbbbbbbaaacbbbb',
      'bbbbbbbbaaacbbbb',
      'bbbbbbbbccccbbbb',
      'bbbbaaacbbbbbbbb',
      'bbbbaaacbbbbbbbb',
      'bbbbaaacbbbbbbbb',
      'bbbbccccbbbbbbbb',
      'aaacbbbbbbbbbbbb',
      'aaacbbbbbbbbbbbb',
      'aaacbbbbbbbbbbbb',
      'ccccbbbbbbbbbbbb',
    ]
  };
  S['tile_stairs_down'] = {
    w: 16, h: 16,
    pal: { 'a': '#a8b0c0:2', 'b': '#7c8494:1', 'c': '#3c4250:0' },
    rows: [
      'bbbbbbbbbbbbaaac',
      'bbbbbbbbbbbbaaac',
      'bbbbbbbbbbbbaaac',
      'bbbbbbbbbbbbcccc',
      'bbbbbbbbaaacbbbb',
      'bbbbbbbbaaacbbbb',
      'bbbbbbbbaaacbbbb',
      'bbbbbbbbccccbbbb',
      'bbbbaaacbbbbbbbb',
      'bbbbaaacbbbbbbbb',
      'bbbbaaacbbbbbbbb',
      'bbbbccccbbbbbbbb',
      'aaacbbbbbbbbbbbb',
      'aaacbbbbbbbbbbbb',
      'aaacbbbbbbbbbbbb',
      'ccccbbbbbbbbbbbb',
    ]
  };
  S['tile_plant'] = {
    w: 16, h: 16,
    pal: { 'k': '#241a10:0', 'p': '#c86838:2', 'q': '#8c4820:1', 'r': '#e08850:3', 'n': '#3c9850:1', 'm': '#276b38:0', 'h': '#6cc878:2', 'f': '#e4b074:2' },
    rows: [
      'ffnnnnnnnhnnnnff',
      'fnnnhnnnnnhnnnff',
      'fnnhnnnnnnnnnnnf',
      'nnnnnnnhnnnmnnff',
      'fnmnnnhnnnnnnnff',
      'fnnnnnnnnnnnnnff',
      'ffnnnnnnnnnnnfff',
      'fffnnnnnnnffffff',
      'fffnnmnnnnffffff',
      'ffffnnnnnfffffff',
      'fffqqqnqqqqqqfff',
      'ffffrrrrrrrrffff',
      'ffffkppppppkffff',
      'ffffkppppppkffff',
      'ffffkppppppkffff',
      'ffffkkkkkkkkffff',
    ]
  };
  S['tile_desk'] = {
    w: 16, h: 16,
    pal: { 'a': '#d8a868:2', 'b': '#c8945c:1', 'c': '#7c4e28:0', 'd': '#603c1c:0', 'w': '#f8f8f4:3', 'l': '#c0c0c0:2', 'p': '#3878c8:1' },
    rows: [
      'aaaaaaaaaaaaaaaa',
      'aaccccccaaaaaaaa',
      'aacwwwwcaapaaaaa',
      'aacllllcaaapaaaa',
      'aacwwwwcaaaapaaa',
      'aacllllcaaaaaaaa',
      'aaaaaaaaaaaaaaaa',
      'cccccccccccccccc',
      'bbbbbbbbbbbbbbbb',
      'bbbbbbbbbbbbbbbb',
      'bbbbbccccccbbbbb',
      'bbbbbcddddcbbbbb',
      'bbbbbcdaadcbbbbb',
      'bbbbbccccccbbbbb',
      'bbbbbbbbbbbbbbbb',
      'bbbbbbbbbbbbbbbb',
    ]
  };
  S['tile_machine'] = {
    w: 16, h: 16,
    pal: { 'a': '#f2ecda:3', 'b': '#cfc2a0:2', 'k': '#241a10:0', 'w': '#f0ead8:3', 'r': '#d8402c:2', 'g': '#48c860:3', 'y': '#f0d030:2', 'e': '#e83828:2', 't': '#9098a0:1', 's': '#303840:0', 'l': '#d0d8e0:3', 'm': '#8c5c30:1' },
    rows: [
      'aaaaaaaabbbbbbbb',
      'aaaaaaaabbbbbbbb',
      'aakkkkkkkkkkkkbb',
      'aakrrrrrrrrrrkbb',
      'aakrrrrrrrrrrkbb',
      'aakwgwwywwewwkbb',
      'aakwwwwwwwwwwkbb',
      'aakwwwwwwwwwwkbb',
      'bbkttttttttttkaa',
      'bmktlstlstlstkma',
      'bmktsstsstsstkma',
      'bmktsstsstsstkma',
      'bmkkkkkkkkkkkkma',
      'bmmmmmmmmmmmmmma',
      'bmmmmmmmmmmmmmma',
      'bbbbbbbbaaaaaaaa',
    ]
  };
  S['tile_lab_table'] = {
    w: 16, h: 16,
    pal: { 'a': '#d0d4d8:3', 'b': '#9098a0:2', 'c': '#585c60:0', 'd': '#f2ecda:3', 'e': '#cfc2a0:2' },
    rows: [
      'ddddddddeeeeeeee',
      'ddddddddeeeeeeee',
      'ddddddddeeeeeeee',
      'bbbbbbbbbbbbbbbb',
      'aaaaaaaaaaaaaaaa',
      'aaaaaaaaaaaaaaaa',
      'aaaaaaaaaaaaaaaa',
      'aaaaaaaaaaaaaaaa',
      'aaaaaaaaaaaaaaaa',
      'aaaaaaaaaaaaaaaa',
      'bbbbbbbbbbbbbbbb',
      'eecceeeeddddccdd',
      'eecceeeeddddccdd',
      'eecceeeeddddccdd',
      'eecceeeeddddccdd',
      'eeeeeeeedddddddd',
    ]
  };
  S['tile_lab_table_item'] = {
    w: 16, h: 16,
    pal: { 'a': '#d0d4d8:3', 'b': '#9098a0:2', 'c': '#585c60:0', 'd': '#f2ecda:3', 'e': '#cfc2a0:2', 'o': '#e8e0c8:3', 'p': '#c0b890:1', 'f': '#7cc0e0:2', 'h': '#4888ac:0', 'n': '#ffffff:3' },
    rows: [
      'ddddddhfffheeeee',
      'ddddddfffffeeeee',
      'ddddddfnfnfeeeee',
      'bbbbbpfffffbbbbb',
      'aaaaappfffpaaaaa',
      'aaaaapoooopaaaaa',
      'aaaaappppppaaaaa',
      'aaaaaaaaaaaaaaaa',
      'aaaaaaaaaaaaaaaa',
      'aaaaaaaaaaaaaaaa',
      'bbbbbbbbbbbbbbbb',
      'eecceeeeddddccdd',
      'eecceeeeddddccdd',
      'eecceeeeddddccdd',
      'eecceeeeddddccdd',
      'eeeeeeeedddddddd',
    ]
  };
  S['tile_cake'] = {
    w: 16, h: 16,
    pal: { 'm': '#b8824c:2', 'v': '#8c5c30:1', 'p': '#f4a8c0:3', 'q': '#e080a0:2', 'w': '#f8f0e8:3', 'x': '#e0d4c4:2', 'y': '#f0d030:2', 'n': '#48a860:2', 'u': '#3878c8:2', 'o': '#f0a830:3', 'e': '#f8e070:3', 'k': '#241a10:0', 'f': '#e4b074:2' },
    rows: [
      'ffffffofefofffff',
      'ffffffyfnfufffff',
      'ffffffyfnfufffff',
      'ffffffyfnfufffff',
      'ffffkkkkkkkkffff',
      'ffffkxxxxxxkffff',
      'ffffkwwwwwwkffff',
      'ffffkkkkkkkkffff',
      'ffkkkkkkkkkkkkff',
      'ffkqqqqqqqqqqkff',
      'ffkppppppppppkff',
      'ffkppppppppppkff',
      'ffkkkkkkkkkkkkff',
      'vvvvvvvvvvvvvvvv',
      'mmmmmmmmmmmmmmmm',
      'mmmmmmmmmmmmmmmm',
    ]
  };
  S['tile_balloon'] = {
    w: 16, h: 16,
    pal: { 'a': '#e4b074:2', 'b': '#c8945c:1', 'c': '#7c4e28:0', 'd': '#f8d8a8:3', 'r': '#e04040:2', 'y': '#f0c030:2', 'u': '#3878c8:2', 's': '#303840:0', 'w': '#ffffff:3', 'k': '#241a10:0' },
    rows: [
      'aaadaaaaaaadaaaa',
      'aaaaaadakkkkkdaa',
      'aaakkkkkkwyykaaa',
      'ccckwrrkkyyykccc',
      'bbbkrrrkkyyykbbb',
      'bbbkrrkkkkkykdbb',
      'bbbkrrkwuukykbbb',
      'ccckrrkuuukkkccc',
      'aaakkkkuuusdaaaa',
      'aaaaaskuuskaadaa',
      'aaaaaskuuskaaaaa',
      'ccccccskskkccccc',
      'bbbdbbbssbbdbbbb',
      'bbbbbbdssbbbbdbb',
      'bbbbbbbbbbbbbbbb',
      'cccccccccccccccc',
    ]
  };
  S['tile_present'] = {
    w: 16, h: 16,
    pal: { 'a': '#e4b074:2', 'b': '#c8945c:1', 'c': '#7c4e28:0', 'd': '#f8d8a8:3', 'r': '#d8402c:2', 's': '#a82818:1', 'g': '#f0c030:3', 'h': '#c89820:2', 'k': '#241a10:0' },
    rows: [
      'aaadaaaaaaadaaaa',
      'aaaaaadaaaaaadaa',
      'aaaahhhaahhhaaaa',
      'cccchghhhhghcccc',
      'bbbdhghhhhghbbbb',
      'bbbbhhhbbhhhbdbb',
      'bbbkkkkggkkkkbbb',
      'ccckrrrggrrrkccc',
      'aaakrrrggrrrkaaa',
      'aaassssggssssdaa',
      'aaakrrrggrrrkaaa',
      'ccckrrrggrrrkccc',
      'bbbkrrrggrrrkbbb',
      'bbbkkkkggkkkkdbb',
      'bbbbbbbbbbbbbbbb',
      'cccccccccccccccc',
    ]
  };
  S['tile_sofa'] = {
    w: 16, h: 16,
    pal: { 'a': '#e4b074:2', 'b': '#c8945c:1', 'c': '#7c4e28:0', 'd': '#f8d8a8:3', 't': '#2f9080:1', 'u': '#1f6858:0', 'h': '#5cb8a8:2', 'k': '#241a10:0' },
    rows: [
      'aaadaaaaaaadaaaa',
      'aaaaaadaaaaaadaa',
      'auuhhhhhhhhhhuua',
      'cuuttttukttttuuc',
      'buuttttukttttuub',
      'buuttttukttttuub',
      'buuttttukttttuub',
      'cuuttttukttttuuc',
      'auuttttukttttuua',
      'auuttttukttttuua',
      'auuttttukttttuua',
      'cuuttttukttttuuc',
      'buuttttukttttuub',
      'buuuuuuuuuuuuuub',
      'bbbbbbbbbbbbbbbb',
      'cccccccccccccccc',
    ]
  };
  S['tile_fridge'] = {
    w: 16, h: 16,
    pal: { 'a': '#e4b074:2', 'b': '#c8945c:1', 'c': '#7c4e28:0', 'd': '#f8d8a8:3', 'w': '#eef0f0:3', 's': '#c8ccd0:2', 'h': '#484850:0', 'k': '#241a10:0' },
    rows: [
      'aaadaaaaaaadaaaa',
      'aaakkkkkkkkkkkaa',
      'aaakwwwwwwwwhkaa',
      'ccckwwwwwwwwhkcc',
      'bbbkwwwwwwwwhkbb',
      'bbbkwwwwwwwwhkbb',
      'bbbkwwwwwwwwwkbb',
      'cccssssssssssscc',
      'aaakwwwwwwwwwkaa',
      'aaakwwwwwwwwhkaa',
      'aaakwwwwwwwwhkaa',
      'ccckwwwwwwwwhkcc',
      'bbbkwwwwwwwwhkbb',
      'bbbkwwwwwwwwwkbb',
      'bbbsssssssssssbb',
      'cccccccccccccccc',
    ]
  };
  S['tile_stove'] = {
    w: 16, h: 16,
    pal: { 'a': '#e4b074:2', 'b': '#c8945c:1', 'c': '#7c4e28:0', 'd': '#f8d8a8:3', 'm': '#4c4c56:1', 'n': '#383840:0', 'o': '#101014:0', 's': '#14283c:0', 'l': '#3868a0:2', 'h': '#b0b0b8:2', 'k': '#241a10:0' },
    rows: [
      'aaadaaaaaaadaaaa',
      'annnnnnnnnnnnnna',
      'annnonnonnonnona',
      'cnnnnnnnnnnnnnnc',
      'bkmmmmmmmmmmmmkb',
      'bkmmmmmmmmmmmmkb',
      'bkmkkkkkkkkkkmkb',
      'ckmksssssssskmkc',
      'akmkslllsssskmka',
      'akmkslllsssskmka',
      'akmkslllsssskmka',
      'ckmksssssssskmkc',
      'bkmkkkkkkkkkkmkb',
      'bkmmmmmmmmmmmmkb',
      'bkkhhhhhhhhhhkkb',
      'cccccccccccccccc',
    ]
  };
  S['item_ball'] = {
    w: 16, h: 16,
    pal: { 'k': '#241a10:0', 'm': '#c8a068:2', 'n': '#a07840:1', 'w': '#f0d8a8:3', 's': '#6c4828:0' },
    rows: [
      '................',
      '................',
      '.......kk.......',
      '......kssk......',
      '.....kskksk.....',
      '.....kmmmmmk....',
      '....kmwmmmmmk...',
      '...kmwwmmnnnnk..',
      '...kmmmmmnnnnk..',
      '...kmmmmmnnnnk..',
      '...kmmmmmnnnnk..',
      '....kmmmmmmmk...',
      '.....kmmmmmk....',
      '......kkkkk.....',
      '................',
      '................',
    ]
  };
  S['emote_alert'] = {
    w: 16, h: 16,
    pal: { 'w': '#ffffff:3', 'k': '#241a10:0', 'i': '#241a10:0' },
    rows: [
      '................',
      '.....kkkkkk.....',
      '....kwwwwwwk....',
      '...kwwwiwwwwk...',
      '...kwwwiwwwwk...',
      '...kwwwiwwwwk...',
      '...kwwwwwwwwk...',
      '....kwwiwwwk....',
      '.....kwkkkk.....',
      '......k.........',
      '.....k..........',
      '................',
      '................',
      '................',
      '................',
      '................',
    ]
  };
  S['emote_heart'] = {
    w: 16, h: 16,
    pal: { 'w': '#ffffff:3', 'k': '#241a10:0', 'r': '#e04058:1' },
    rows: [
      '................',
      '.....kkkkkk.....',
      '....kwwwwwwk....',
      '...kwwrrwrrwk...',
      '...kwrrrrrrrk...',
      '...kwwrrrrrwk...',
      '...kwwwrrwwwk...',
      '....kwwwwwwk....',
      '.....kwkkkk.....',
      '......k.........',
      '.....k..........',
      '................',
      '................',
      '................',
      '................',
      '................',
    ]
  };
  S['emote_music'] = {
    w: 16, h: 16,
    pal: { 'w': '#ffffff:3', 'k': '#241a10:0', 'n': '#241a10:0' },
    rows: [
      '................',
      '.....kkkkkk.....',
      '....kwwwwwwk....',
      '...kwwwnnwwwk...',
      '...kwwwnnwwwk...',
      '...kwwwnwwwwk...',
      '...kwnnnwwwwk...',
      '....knnwwwwk....',
      '.....kwkkkk.....',
      '......k.........',
      '.....k..........',
      '................',
      '................',
      '................',
      '................',
      '................',
    ]
  };
  S['icon_bean'] = {
    w: 8, h: 8,
    pal: { 'k': '#241a10:0', 'm': '#c8a068:2', 'n': '#a07840:1' },
    rows: [
      '..kkkk..',
      '.kmmmmk.',
      'kmmmmmmk',
      'kmmmnnmk',
      'kmmmnnmk',
      '.kmmmmk.',
      '..kmmk..',
      '...kk...',
    ]
  };
  S['icon_heart'] = {
    w: 8, h: 8,
    pal: { 'k': '#241a10:0', 'r': '#e04058:2' },
    rows: [
      '.kk..kk.',
      'krrkkrrk',
      'rrrrrrrr',
      'krrrrrrk',
      '.krrrrk.',
      '..krrk..',
      '...kk...',
      '........',
    ]
  };
  S['icon_star'] = {
    w: 8, h: 8,
    pal: { 'k': '#241a10:0', 'y': '#f0c030:3' },
    rows: [
      '..kyyk..',
      '.kkyykk.',
      'kyyyyyyk',
      '.kyyyyk.',
      'kyyyyyyk',
      'yykkkkyy',
      'kyykkyyk',
      '.kk..kk.',
    ]
  };
  S['badge_compassion'] = {
    w: 16, h: 16,
    pal: { 'k': '#1c1408:0', 'g': '#f6dc84:3', 'h': '#c89830:1', 'p': '#a860d8:2', 'q': '#6c2f96:1', 'w': '#ffffff:3' },
    rows: [
      '................',
      '................',
      '...kk......kk...',
      '..khhk....khhk..',
      '.khgwhk..khpphk.',
      'khppgphkkhpppphk',
      'khppppphhppppphk',
      'khpppppppppppphk',
      '.khpppppqqqqqhk.',
      '..khppppqqqqhk..',
      '...khpppqqqhk...',
      '....khppqqhk....',
      '.....khpphk.....',
      '......khhk......',
      '.......kk.......',
      '................',
    ]
  };
  S['shadow_oval'] = {
    w: 16, h: 8,
    pal: { 's': '#000000:0' },
    rows: [
      '................',
      '...ssssssssss...',
      '..ssssssssssss..',
      '.ssssssssssssss.',
      '.ssssssssssssss.',
      '..ssssssssssss..',
      '...ssssssssss...',
      '................',
    ]
  };
})();
