"""Kind and FriendDex entry for each of the 151 creatures."""

# name -> (kind, dex entry)
LORE = {
 'BUNNIP':   ('FLUFF', 'A palmful of warm fluff. Thumps a hind foot when pleased, which is often.'),
 'HOPPARD':  ('FLUFF', 'Its ears turn like dishes to find the softest voice in the room.'),
 'LOPALOPE': ('FLUFF', 'Big, calm and slow to startle. Leans its whole weight on friends it trusts.'),
 'CHIRPLET': ('PEEP',  'Peeps at everything, including its own reflection. Follows the first kind face it sees.'),
 'PECKLIN':  ('PEEP',  'Practises crowing at dawn and gets it wrong with tremendous confidence.'),
 'PLUMEHEN': ('PEEP',  'Adopts anything smaller than herself. Remembers a hundred faces and every kindness.'),
 'PIGLIN':   ('SNOUT', 'Wags its curly tail so hard the rest of it wobbles.'),
 'SNOUTLE':  ('SNOUT', 'Can smell an apple through a closed door. Will discuss the door at length.'),
 'HOGGARTH': ('SNOUT', 'Sunbathes with great commitment. Dreams in colour and snores in harmony.'),
 'CALFKIN':  ('MOO',   'All legs and eyelashes. Sticks close to whoever it decided is family.'),
 'MOOVEN':   ('MOO',   'Hums while grazing. Has a favourite patch of grass and firm opinions about it.'),
 'BELLOWE':  ('MOO',   'Its low call carries across three fields and settles every argument in them.'),
 'LAMBKIN':  ('WOOL',  'Bounces instead of walking. Has not yet worked out how to stop.'),
 'WOOLIN':   ('WOOL',  'A cloud that answers to its name. Warm to lean on in any weather.'),
 'FLEECIA':  ('WOOL',  'Counts itself to fall asleep. Nearby creatures fall asleep first.'),
 'KIDLET':   ('HORN',  'Climbs everything, including you. Delighted to be up there, unsure how to get down.'),
 'CLAMBER':  ('HORN',  'Balances on fence posts for fun. Has never once fallen, it says.'),
 'CAPRIX':   ('HORN',  'Rectangular pupils, mischievous grin, strong views on gates.'),
 'DUCKLIN':  ('QUACK', 'Imprints on the first gentle face it meets. Please be that face.'),
 'PADDLER':  ('QUACK', 'Paddles in perfect circles and considers this a complete morning.'),
 'MALLARCH': ('QUACK', 'Quacks in steady four-four time. Waterproof, cheerful, quietly judgemental.'),
 'GOSLET':   ('HONK',  'Its honk is still a squeak. It is very serious about the squeak.'),
 'HONKLER':  ('HONK',  'Marches in a line behind anyone it trusts, whether or not they agreed.'),
 'GANDARE':  ('HONK',  'Fearless beyond sense, loyal beyond reason. Its honk has ended arguments.'),
 'BEANLET':  ('LEAF',  'A sprouted bean with opinions. Turns to face whoever is kindest.'),
 'SPROUTOR': ('LEAF',  'Grows an inch on a good day. Applauds rain.'),
 'VERDANTHA':('LEAF',  'Old and green and patient. Shelters smaller creatures under its leaves.'),
 'NIBBLET':  ('FLUFF', 'Stuffs both cheeks, then forgets why. Naps in the shape of a comma.'),
 'GNAWLIN':  ('FLUFF', 'Tidies its burrow constantly and invites everyone to come and see it.'),
 'BURROWL':  ('FLUFF', 'Digs rooms for friends who have nowhere to sleep.'),
 'MEWLIN':   ('PAW',   'Fits in a boot. Chooses the boot over any bed you buy it.'),
 'PURRAX':   ('PAW',   'Purrs at a frequency that makes worries feel smaller.'),
 'VELVETTE': ('PAW',   'Moves like poured water. Sits exactly where you are working.'),
 'PUPPLET':  ('PAW',   'Trips over its own feet at speed and is thrilled about it.'),
 'WOOFEN':   ('PAW',   'Carries one favourite stick everywhere as identification.'),
 'LOYALDO':  ('PAW',   'Waits by the door with unreasonable faith. Always right in the end.'),
 'FINLET':   ('SPLASH','A thumb-sized flicker of blue. Blows bubbles to say hello.'),
 'SPLASHIN': ('SPLASH','Leaps for the joy of the splash, then checks that you saw.'),
 'TIDALLE':  ('SPLASH','Glides in long slow arcs. The water goes quiet around it.'),
 'GRUBLET':  ('BUZZ',  'Munches steadily through a leaf and leaves a tidy edge.'),
 'COCOONIE': ('BUZZ',  'Asleep, and busy. Something wonderful is happening in there.'),
 'FLUTTERA': ('BUZZ',  'Wings like stained glass. Lands on the shoulder of the calmest person present.'),
 'TADPOLL':  ('SPLASH','All tail and enthusiasm. Wiggles when spoken to.'),
 'HOPPLET':  ('SPLASH','Sings after rain in a voice far too big for it.'),
 'RIBBITON': ('SPLASH','Its chorus carries across the marsh. Keeps time for the whole pond.'),
 'SHELLET':  ('SHELL', 'Carries its house and its bedtime with it.'),
 'PADDLETOP':('SHELL', 'Slow on land, sudden in water. Surprises everyone exactly once.'),
 'TERRAPINE':('SHELL', 'Has seen many summers. Offers its shell as shade to smaller friends.'),
 'OWLET':    ('PEEP',  'Two enormous eyes and a small amount of bird.'),
 'HOOTLE':   ('PEEP',  'Asks who, repeatedly, and waits politely for an answer.'),
 'NOCTURNA': ('PEEP',  'Flies without a sound. Watches over the sleeping fields.'),
 'CUBBIN':   ('PAW',   'Round, clumsy and permanently hungry for berries.'),
 'BRAMBLEAR':('PAW',   'Knows every berry patch for miles and shares all of them.'),
 'GRIZZLOAM':('PAW',   'Enormous and gentle. Naps through most disagreements.'),
 'KITSLET':  ('PAW',   'Pounces on leaves and misses. Tries again immediately.'),
 'RUSSELLE': ('PAW',   'Quick, clever and fond of tricks that harm nobody.'),
 'VULPINA':  ('PAW',   'Its tail is a lantern in the dark for anyone lost.'),
 'SPORELET': ('LEAF',  'Pops up overnight after rain, cheerful and slightly damp.'),
 'CAPPLIN':  ('LEAF',  'Its cap keeps two small friends dry.'),
 'MYCELIA':  ('LEAF',  'Quietly connects the whole forest. Knows what every tree is feeling.'),
 'PRICKLET': ('PAW',   'Curls into a ball when shy, which is most of the time.'),
 'HEDGEROW': ('PAW',   'Snuffles through the undergrowth at dusk, greeting everyone it meets.'),
 'FLITTLE':  ('DUSK',  'Hangs upside down and believes it looks dignified.'),
 'DUSKWING': ('DUSK',  'Navigates by sound. Never bumps into anyone, ever.'),
 'PINCHLET': ('SHELL', 'Waves both claws when happy, which reads as a threat and is not.'),
 'SHORECLAW':('SHELL', 'Rearranges the beach according to its own private plan.'),
 'COILET':   ('BUZZ',  'Loops itself into a neat spiral to sleep.'),
 'MEADOWYRM':('BUZZ',  'Threads through long grass, leaving a tidy green path.'),
 'COOLET':   ('COO',   'Bobs its head to music only it can hear.'),
 'CITYWING': ('COO',   'Finds its way home from anywhere. Underrated, unbothered, iridescent.'),
 'TOFULET':  ('GLOW',  'Soft, pale and endlessly adaptable. Takes on the mood of the room.'),
 'TEMPETH':  ('GLOW',  'Firm, nutty and dependable. Holds a whole group together.'),
 'KALEAF':   ('LEAF',  'Dark green and quietly smug about its vitamins.'),
 'KALESTRA': ('LEAF',  'Unfurls enormous leaves to shade the entire garden.'),
 'OATLING':  ('LEAF',  'Rustles softly. Smells of a warm breakfast.'),
 'OATERNAL': ('LEAF',  'Sways in the field and comforts everyone who passes.'),
 'BUZZLET':  ('BUZZ',  'Dusted with pollen. Visits every flower and thanks each one.'),
 'POLLENAIRE':('BUZZ', 'Keeps the meadow blooming. Takes nothing that is not offered.'),
 'ANTLET':   ('BUZZ',  'Carries things eleven times its size, cheerfully.'),
 'FORMICORE':('BUZZ',  'Organises everything. Has a plan for the colony and for the weather.'),
 'BUBBLIN':  ('SPLASH','Speaks entirely in bubbles. Somehow you understand it.'),
 'GLIMMERFIN':('SPLASH','Catches the light and hands it back prettier.'),
 'SEALET':   ('SPLASH','Round, whiskered and permanently astonished.'),
 'SELKIE':   ('SPLASH','Sings low notes under the water that carry for miles.'),
 'OTTERLET': ('SPLASH','Holds a friend by the paw so neither drifts away while sleeping.'),
 'RIVERSONG':('SPLASH','Cracks shells on its belly and shares the good ones.'),
 'SQUEAKLET':('FLUFF', 'Small enough to sleep in a teacup. Does.'),
 'WHISKERO': ('FLUFF', 'Maps every room by whisker and never forgets the way out.'),
 'ACORNIP':  ('FLUFF', 'Buries acorns and forgets them, which is how forests happen.'),
 'TUFTAIL':  ('FLUFF', 'Its tail is a parasol, a blanket and a semaphore flag.'),
 'FOALIN':   ('HOOF',  'Legs it has not grown into yet. Runs anyway.'),
 'GALLOPRA': ('HOOF',  'Runs for the pleasure of running and comes back for the company.'),
 'BRAYLET':  ('HOOF',  'Ears far too big, heart to match.'),
 'BURRONNE': ('HOOF',  'Stubborn only about unsafe ground. It is always right.'),
 'POULTLET': ('PEEP',  'Chirrs and blushes when complimented.'),
 'GOBBLARA': ('PEEP',  'Fans a tail like a sunrise. Deserves every holiday off.'),
 'PEALET':   ('PEEP',  'Practises its display in front of puddles.'),
 'PLUMARIS': ('PEEP',  'Opens a hundred eyes of colour and silences the room.'),
 'CYGNIP':   ('QUACK', 'Grey, gawky, and going to be magnificent.'),
 'SWANESSA': ('QUACK', 'Serene above the water, working furiously below.'),
 'SPOTLET':  ('PAW',   'Stalks a butterfly for an hour, then lets it go.'),
 'LYNXARA':  ('PAW',   'Silent in snow. Tufted ears catch the smallest sound.'),
 'WOLFLET':  ('PAW',   'Practises howling. It comes out as a squeak and everyone applauds.'),
 'LUNARUFF': ('PAW',   'Sings to the moon with its whole family and means every note.'),
 'FAWNLET':  ('HORN',  'Wobbles, hides, peeks. Braver every day.'),
 'ANTLERIA': ('HORN',  'Carries a small forest on its head and steps around every nest.'),
 'PANDLET':  ('PAW',   'Falls out of things. Considers this a hobby.'),
 'BAMBOOM':  ('PAW',   'Eats, sleeps, rolls downhill. A complete philosophy.'),
 'TRUFFLET': ('LEAF',  'Grows in secret under the oaks and smells like treasure.'),
 'FUNGARO':  ('LEAF',  'Glows faintly at night to guide lost creatures home.'),
 'CARROTOT': ('LEAF',  'Half root, half rascal. Crunchy and enormously pleased with itself.'),
 'ROOTARCH': ('LEAF',  'Its roots run deep enough to find water for the whole field.'),
 'PUMPLET':  ('LEAF',  'Rolls where it wants to go. Steering is aspirational.'),
 'GOURDIAN': ('LEAF',  'Keeps the harvest safe and hands it out fairly.'),
 'SPROUTIE': ('LEAF',  'Two leaves and boundless optimism.'),
 'GREENGALE':('LEAF',  'Rides the wind on leaf-wings, scattering seeds as it goes.'),
 'LARVLET':  ('BUZZ',  'Inches along, measuring the world in its own lengths.'),
 'PRISMWING':('BUZZ',  'Splits sunlight into colour wherever it lands.'),
 'NYMPHLET': ('BUZZ',  'Lives underwater until the day it decides not to.'),
 'GLIDEWING':('BUZZ',  'Hovers perfectly still, then is somewhere else entirely.'),
 'TREEPLET': ('SPLASH','Sticks to windows to watch what you are doing.'),
 'CANOPPY':  ('SPLASH','Lives high in the leaves and drops in for conversation.'),
 'PADDLIN':  ('SHELL', 'Steers with its front flippers and grins the whole time.'),
 'OCEANOR':  ('SHELL', 'Crosses oceans alone and returns to the same warm beach.'),
 'COCKLET':  ('PEEP',  'Announces the dawn eleven minutes early, every day.'),
 'ROOSTAR':  ('PEEP',  'Guards the whole flock and takes the job personally.'),
 'PENGLET':  ('QUACK', 'Slides everywhere on its belly because walking is slower.'),
 'TUXEDON':  ('QUACK', 'Formally dressed for every occasion, including swimming.'),
 'ALPACLET': ('WOOL',  'Hums when content. Spits only at genuine rudeness.'),
 'FLUFFANDO':('WOOL',  'A tower of warm wool with a very small face at the top.'),
 'PIGEONIS': ('COO',   'The legendary city bird. Underrated, unbothered, iridescent, and always home.'),
 'MOOCHU':   ('GLOW',  'A spirit of golden flakes. Makes any meal, and any mood, better.'),
 'BEANWISE': ('LEAF',  'Ancient and patient. Said to remember every bean ever planted.'),
 'TOFURION': ('GLOW',  'A calm white giant. Takes on the flavour of whatever kindness surrounds it.'),
 'HAYWAIN':  ('LEAF',  'Smells of summer afternoons. Warm to sleep against.'),
 'CLOVERA':  ('LEAF',  'Four leaves, always. Luck follows it around, mildly embarrassed.'),
 'SUNPETAL': ('LEAF',  'Turns its face to follow anyone who smiles at it.'),
 'DANDELUFF':('LEAF',  'One wish per seed, and it gives them all away.'),
 'BADGERON': ('PAW',   'Digs a home with room for guests and insists that you stay.'),
 'MOLEKIN':  ('PAW',   'Sees almost nothing and knows exactly where everything is.'),
 'RACCOONA': ('PAW',   'Washes its food, your keys, and anything left unattended.'),
 'POSSUMBER':('PAW',   'Plays dead dramatically, then peeks to check the reviews.'),
 'FERRETTA': ('PAW',   'Sixty percent noodle. Dances sideways when excited.'),
 'LLAMANDA': ('WOOL',  'Guards smaller creatures from absolutely anything. Very tall about it.'),
 'CAMELIA':  ('HOOF',  'Carries water and gossip across long distances.'),
 'QUOKKINE': ('FLUFF', 'Cannot stop smiling. Genuinely does not want to.'),
 'CAPYBLISS':('FLUFF', 'Friend to every species. Has never once been in a hurry.'),
 'SLOTHEA':  ('PAW',   'Arrives eventually. Worth the wait every time.'),
 'HERONESS': ('QUACK', 'Stands motionless in the shallows, thinking long thoughts.'),
 'ROBINETTE':('PEEP',  'Sings first in the morning and last at night.'),
 'STARLINGA':('PEEP',  'Flies in vast patterns with a thousand friends and never touches one.'),
}

# kind -> (favourite food, second favourite, cry sound, move list as (level, move))
KINDS = {
 'FLUFF': ('CARROT', 'LETTUCE', 'cry_bunny',
           [(1,'NUZZLE'),(5,'HOP'),(9,'PUPPY EYES'),(14,'ZOOMIES'),(21,'BINKY'),(29,'GENTLE FACT')]),
 'PEEP':  ('SEEDS', 'OATS', 'cry_chick',
           [(1,'PEEP'),(5,'TAP DANCE'),(9,'FLUFF UP'),(14,'HAPPY DANCE'),(22,'WING HUG'),(30,'MOTHER HEN')]),
 'SNOUT': ('APPLE', 'OATS', 'cry_pig',
           [(1,'OINK'),(6,'MUD BATH'),(10,'SNOUT BOOP'),(15,'BELLY FLOP'),(23,'BIG SNUGGLE'),(30,'GENTLE FACT')]),
 'MOO':   ('HAY', 'OATS', 'cry_cow',
           [(1,'MOO'),(6,'HEAD BONK'),(11,'LICK'),(16,'MOO-D BOOST'),(24,'GENTLE FACT'),(31,'BIG SNUGGLE')]),
 'WOOL':  ('HAY', 'LETTUCE', 'cry_sheep',
           [(1,'BAA'),(5,'BOUNCE'),(10,'WOOL HUG'),(15,'COUNT SHEEP'),(23,'PUPPY EYES'),(30,'BIG SNUGGLE')]),
 'HORN':  ('APPLE', 'LETTUCE', 'cry_goat',
           [(1,'BLEAT'),(5,'PLAY BUTT'),(10,'CLIMB'),(15,'GOAT YOGA'),(22,'STARE DOWN'),(29,'GENTLE FACT')]),
 'QUACK': ('SEEDS', 'LETTUCE', 'cry_duck',
           [(1,'QUACK'),(5,'SPLASH'),(10,'WADDLE'),(14,'PADDLE'),(21,'WING FLAP'),(28,'PUPPY EYES')]),
 'HONK':  ('SEEDS', 'OATS', 'cry_goose',
           [(1,'HONK'),(6,'WING FLAP'),(11,'WADDLE'),(16,'STARE DOWN'),(23,'PEACE HONK'),(30,'GENTLE FACT')]),
 'PAW':   ('OATS', 'APPLE', 'cry_bunny',
           [(1,'NOSE BOOP'),(5,'TAIL WAG'),(10,'PURR'),(15,'SLOW BLINK'),(22,'BIG SNUGGLE'),(29,'GENTLE FACT')]),
 'HOOF':  ('HAY', 'CARROT', 'cry_cow',
           [(1,'NOSE BOOP'),(6,'HEAD BONK'),(11,'LICK'),(16,'SLOW STROLL'),(23,'MOO-D BOOST'),(30,'GENTLE FACT')]),
 'LEAF':  ('SEEDS', 'LETTUCE', 'cry_chick',
           [(1,'RUSTLE'),(6,'SUNSOAK'),(11,'LEAF SHOWER'),(16,'ROOT DOWN'),(23,'SHARE SNACK'),(30,'GENTLE FACT')]),
 'SPLASH':('LETTUCE', 'SEEDS', 'cry_duck',
           [(1,'BUBBLE'),(5,'SPLASH'),(10,'PADDLE'),(15,'DIVE'),(22,'HAPPY DANCE'),(29,'GENTLE FACT')]),
 'BUZZ':  ('SEEDS', 'APPLE', 'cry_chick',
           [(1,'ANTENNAE'),(5,'FLUTTER'),(10,'POLLEN PUFF'),(15,'HAPPY DANCE'),(22,'SHARE SNACK'),(29,'GENTLE FACT')]),
 'SHELL': ('LETTUCE', 'OATS', 'cry_goat',
           [(1,'NOSE BOOP'),(6,'SHELL HIDE'),(11,'SLOW STROLL'),(16,'BIG YAWN'),(23,'COUNT SHEEP'),(30,'GENTLE FACT')]),
 'COO':   ('SEEDS', 'OATS', 'cry_pigeon',
           [(1,'COO'),(5,'HEAD BOB'),(10,'WING FLAP'),(15,'HOMING'),(24,'PEACE HONK'),(32,'CITY WISDOM')]),
 'DUSK':  ('APPLE', 'SEEDS', 'cry_bunny',
           [(1,'SQUEAK'),(6,'FLUTTER'),(11,'SLOW BLINK'),(16,'BIG YAWN'),(23,'WING HUG'),(30,'GENTLE FACT')]),
 'GLOW':  ('OATS', 'SEEDS', 'cry_sheep',
           [(1,'WARM GLOW'),(6,'SHARE SNACK'),(11,'SOFT HUM'),(16,'BIG SNUGGLE'),(24,'GRATITUDE'),(32,'CITY WISDOM')]),
}

# charm moves the roster needs that the game does not have yet
NEW_MOVES = {
 'NOSE BOOP':   ('CUTE',  38, 30, '{A} booped with its nose!'),
 'TAIL WAG':    ('CUTE',  45, 25, '{A} wagged its whole back half!'),
 'PURR':        ('HEART', 58, 20, '{A} purred until the room felt softer.'),
 'SLOW BLINK':  ('HEART', 70, 15, '{A} gave a slow, trusting blink.'),
 'BIG YAWN':    ('CUTE',  62, 15, '{A} yawned enormously. It is catching!'),
 'SLOW STROLL': ('LOGIC', 55, 20, '{A} ambled past, in no hurry at all.'),
 'RUSTLE':      ('CUTE',  38, 30, '{A} rustled its leaves.'),
 'SUNSOAK':     ('HEART', 50, 20, '{A} soaked up the sun and shared the warmth.'),
 'LEAF SHOWER': ('CUTE',  62, 15, '{A} showered everyone in soft green leaves!'),
 'ROOT DOWN':   ('LOGIC', 75, 10, '{A} rooted itself. It will not be moved.'),
 'BUBBLE':      ('CUTE',  38, 30, '{A} blew a stream of bubbles!'),
 'DIVE':        ('CUTE',  70, 12, '{A} dived and surfaced, beaming.'),
 'ANTENNAE':    ('CUTE',  38, 30, '{A} waggled its antennae hello.'),
 'FLUTTER':     ('CUTE',  50, 25, '{A} fluttered in a happy loop!'),
 'POLLEN PUFF': ('HEART', 62, 15, '{A} puffed golden pollen everywhere!'),
 'SHELL HIDE':  ('LOGIC', 48, 25, '{A} tucked in and waited it out.'),
 'SQUEAK':      ('CUTE',  38, 30, '{A} let out a tiny squeak!'),
 'WARM GLOW':   ('HEART', 55, 20, '{A} glowed with a gentle warmth.'),
 'SOFT HUM':    ('HEART', 68, 15, '{A} hummed a tune with no name.'),
 'SHARE SNACK': ('HEART', 72, 10, '{A} shared its snack. Half each!'),
}
