#!/usr/bin/env node
// Export every piece of player-facing text into COPY.md for editing.
//
//   node tools/export_copy.js
//
// Each block carries an [id]. Edit the text under an id, keep the id line intact,
// and the edits can be applied back to the right place in the source.
//
// {NAME} is the player's name and {RIVAL} the rival's -- the game substitutes these
// at runtime, so leave them in place wherever you want the name to appear.
const fs = require('fs');
const path = require('path');
const { loadGame } = require('./headless');

const ROOT = path.join(__dirname, '..');
const W = loadGame({ quiet: true });
const { MAPS, TEAM, DATA, CREATURES, G } = W;

// Dialogue is sometimes a function of game state; call it with placeholder names
// so the exported copy reads the way the player sees it.
G.state.name = '{NAME}';
G.state.rival = '{RIVAL}';
const resolve = d => (typeof d === 'function' ? d(G) : d);
const lines = v => (Array.isArray(v) ? v : v == null ? [] : [v]).map(String);

const out = [];
const P = s => out.push(s);
const block = (id, note, text) => {
  const ls = lines(text).filter(l => l.trim());
  if (!ls.length) return;
  P(`\n[${id}]${note ? '  — ' + note : ''}`);
  ls.forEach(l => P(l));
};

P('# HACKTIVISTS — Violet Version: all in-game copy');
P('');
P('Generated by `node tools/export_copy.js`. Edit the lines under each `[id]` and send it back.');
P('');
P('- Keep every `[id]` line exactly as it is — that is how edits get matched to the source.');
P('- `{NAME}` is the player\'s name, `{RIVAL}` is the rival\'s. Leave them where you want the name to appear.');
P('- Each line is one textbox page. Splitting a line into two makes two pages; joining them makes one.');
P('- Text wraps at roughly 18 characters per line inside a 2-line box, so keep pages short.');
P('');
P('You do not have to send the whole file back — paste back only the `[id]` blocks you changed.');

// ---------------------------------------------------------------- story scripts
P('\n\n## 1. Story and cutscenes');
P('\nThese live in js/game.js. Line numbers are shown so they can be located exactly.');
const STRING_RE = /'((?:[^'\\]|\\.)*)'/g;
for (const file of ['js/game.js', 'js/battle.js', 'js/ui.js']) {
  const src = fs.readFileSync(path.join(ROOT, file), 'utf8').split('\n');
  const hits = [];
  src.forEach((line, i) => {
    if (!/\b(say|msg|msgWait|sayHold)\s*\(/.test(line) && !/text:\s*\[/.test(line)) return;
    // The player's name is concatenated around the literals, so turn the variables
    // into literals first and then fold the whole concatenation into one string.
    let expr = line.replace(/G\.state\.name/g, "'{NAME}'").replace(/G\.state\.rival/g, "'{RIVAL}'");
    let prev;
    do {
      prev = expr;
      expr = expr.replace(/'((?:[^'\\]|\\.)*)'\s*\+\s*'((?:[^'\\]|\\.)*)'/g, (m, a, b) => "'" + a + b + "'");
    } while (expr !== prev);
    let m, seq = 0;
    STRING_RE.lastIndex = 0;
    while ((m = STRING_RE.exec(expr))) {
      const s = m[1].replace(/\\'/g, "'").replace(/\\\\/g, '\\');
      if (!/\s/.test(s) || s.length < 6) continue;      // skip ids, flags, sprite names
      hits.push({ line: i + 1, seq: ++seq, s });
    }
  });
  if (!hits.length) continue;
  P(`\n### ${file}`);
  for (const h of hits) block(`${path.basename(file, '.js')}:${h.line}.${h.seq}`, '', h.s);
}

// ---------------------------------------------------------------- maps
P('\n\n## 2. Signs, NPCs and world text');
for (const id of Object.keys(MAPS)) {
  const m = MAPS[id];
  const objs = m.objects || [];
  const parts = [];
  objs.forEach((o, i) => {
    const tag = o.id || o.team || `${o.type}${i}`;
    if (o.type === 'sign' || o.type === 'interact') parts.push([`${id}.${tag}`, `${o.type} at ${o.x},${o.y}`, resolve(o.text)]);
    if (o.type === 'npc') {
      const def = o.team && TEAM[o.team] ? Object.assign({}, TEAM[o.team], o) : o;
      if (def.dialog) parts.push([`${id}.${tag}.dialog`, `NPC at ${o.x},${o.y}`, resolve(def.dialog)]);
      if (def.trainer) {
        if (def.trainer.intro) parts.push([`${id}.${tag}.intro`, 'before the battle', resolve(def.trainer.intro)]);
        if (def.trainer.taunt) parts.push([`${id}.${tag}.taunt`, 'battle taunt', def.trainer.taunt]);
        if (def.trainer.win) parts.push([`${id}.${tag}.win`, 'on losing to you', def.trainer.win]);
        if (def.trainer.after) parts.push([`${id}.${tag}.after`, 'afterwards', resolve(def.trainer.after)]);
      }
      if (def.gift) {
        if (def.gift.lines) parts.push([`${id}.${tag}.gift`, 'gives you ' + def.gift.item, resolve(def.gift.lines)]);
        if (def.gift.after) parts.push([`${id}.${tag}.gift_after`, 'afterwards', resolve(def.gift.after)]);
      }
    }
  });
  if (!parts.length) continue;
  P(`\n### ${id} — ${m.name || ''}`);
  parts.forEach(p => block(p[0], p[1], p[2]));
}

// ---------------------------------------------------------------- team
P('\n\n## 3. The team');
P('\n`dialog` is what they say when you talk to them. `quote` is the birthday message');
P('they walk over and deliver the first time you pass — those are the heart of the game.');
for (const k of Object.keys(TEAM)) {
  const t = TEAM[k];
  P(`\n### ${t.name}`);
  block(`team.${k}.dialog`, 'on talking to them', resolve(t.dialog));
  if (t.quote) block(`team.${k}.quote`, 'BIRTHDAY MESSAGE', resolve(t.quote));
}

// ---------------------------------------------------------------- skeptics
P('\n\n## 4. Skeptics (the people you win over)');
for (const k of Object.keys(DATA.SKEPTICS)) {
  const s = DATA.SKEPTICS[k];
  P(`\n### ${k} — "${s.name}"`);
  block(`skeptic.${k}.taunt`, 'opening line', s.taunt);
  block(`skeptic.${k}.win`, 'when you win them over', s.win);
  block(`skeptic.${k}.after`, 'when you talk to them later', s.after);
  (s.args || []).forEach((a, i) => block(`skeptic.${k}.arg${i}`, `argument "${a[0]}"`, a[2].replace('{S}', s.name)));
}

// ---------------------------------------------------------------- items & moves
P('\n\n## 5. Items');
P('\nFormat: `NAME | description`. Renaming an item updates it everywhere.');
for (const k of Object.keys(DATA.ITEMS)) {
  const it = DATA.ITEMS[k];
  block(`item.${k}`, '', `${it.name} | ${it.desc}`);
}

P('\n\n## 6. Charms (battle moves)');
P('\nFormat: `NAME | message shown when used`. {A} is the animal\'s name.');
for (const k of Object.keys(DATA.MOVES)) {
  const mv = DATA.MOVES[k];
  block(`move.${k}`, '', `${mv.name} | ${mv.msg}`);
}

// ---------------------------------------------------------------- creatures
P('\n\n## 7. The 151 animals');
P('\nFormat: `NAME | dex entry`. Renaming here needs the rename tool re-run, so');
P('prefer editing just the entry text unless you want a name changed too.');
for (const c of CREATURES) {
  block(`animal.${c.num}`, '', `${c.name} | ${c.entry}`);
}

const dst = path.join(ROOT, 'COPY.md');
fs.writeFileSync(dst, out.join('\n') + '\n');
const n = out.filter(l => /^\n?\[/.test(l)).length;
console.log(`wrote COPY.md — ${n} editable blocks, ${out.length} lines`);
